FIRE: CommandExecutor Class Reference
CommandExecutor Class Reference
Static Public Member Functions
static int ExecuteCollect (CollectSettings settings, RuntimeContext runtime)
static int ExecuteGenerate (CommonCommandSettings settings, RuntimeContext runtime)
static int ExecuteFileOperations (CommonCommandSettings settings, RuntimeContext runtime)
static int ExecuteInspect (InspectSettings settings, RuntimeContext runtime)
Detailed Description
Definition at line 147 of file Program.cs.
Member Function Documentation
ExecuteCollect()
int CommandExecutor::ExecuteCollect (CollectSettings settings, RuntimeContext runtime) inline static
Definition at line 149 of file Program.cs.
References CollectSettings::ClearDatabase, RuntimeContext(), ConsoleUi::WriteEmptyLine(), and ConsoleUi::WriteLine().
Referenced by Run().
ExecuteFileOperations()
int CommandExecutor::ExecuteFileOperations (CommonCommandSettings settings, RuntimeContext runtime) inline static
Definition at line 186 of file Program.cs.
References RuntimeContext().
ExecuteGenerate()
int CommandExecutor::ExecuteGenerate (CommonCommandSettings settings, RuntimeContext runtime) inline static
Definition at line 172 of file Program.cs.
References RuntimeContext().
Referenced by GenerateCommand::Execute().
ExecuteInspect()
int CommandExecutor::ExecuteInspect (InspectSettings settings, RuntimeContext runtime) inline static
Definition at line 200 of file Program.cs.
References Culture, FIREConfigration::EnsureSupportedConfigurationVersion(), FIRECatalog(), FIREConfigration::Load(), RuntimeContext(), ConsoleUi::WriteEmptyLine(), ConsoleUi::WriteError(), ConsoleUi::WriteInfo(), ConsoleUi::WriteLine(), ConsoleUi::WriteSuccess(), ConsoleUi::WriteTitle(), and ConsoleUi::WriteWarning().
Referenced by InspectCommand::Execute().
The documentation for this class was generated from the following file:
FIRE/FIRE.Console/Program.cs