FIRE: FIREConfigration Class Reference
FIREConfigration Class Reference
Represents the root configuration document loaded from the FIRE configuration YAML file.
Public Member Functions
bool IsConfigurationVersionSupported ()
Checks whether the loaded configuration version matches the supported version.
void EnsureSupportedConfigurationVersion ()
Throws an exception if the configuration version is not supported.
Static Public Member Functions
static FIREConfigration Load (string filePath)
Loads a FIRE configuration from a YAML file on disk.
static FIREConfigration Parse (string yaml)
Parses YAML content into a FIREConfigration instance.
Public Attributes
const decimal SupportedConfigurationVersion = 1.10m
The semantic version of the configuration format currently supported by this build.
decimal ConfigurationVersion { get
Gets or sets the configuration format version.
set
List< string > FilesRootPath { get
Gets or sets the list of root directories to scan for source files during collection.
string DataBasePath { get
Gets or sets the directory path where the SQLite database file is stored.
string DataBaseFileName { get
Gets or sets the name of the SQLite database file (e.g., "fire.db").
string Action { get
Gets or sets the default file operation for all files (Copy, Move, or Link).
string MediaRootPath { get
Gets or sets the media root path variable used in path templates.
string RootPath { get
Gets or sets the base root path for output directories (may contain placeholders).
string SortingPatern { get
Gets or sets the directory sorting path pattern (may contain metadata placeholders).
string FileNamePatern { get
Gets or sets the file name pattern (may contain metadata placeholders).
Dictionary< string, string > StringReplacements { get
Gets or sets a dictionary of global string replacements applied to all resolved paths.
Dictionary< string, FileExtensionConfiguration > FileExtensions { get
Gets or sets a dictionary of file extension-specific configurations.
List< string > FileSorting { get
Gets or sets the ordered list of metadata keys used to sort records before path generation.
string FileSortingOrder { get
Gets or sets the global sorting direction used for FileSorting.
Detailed Description
Represents the root configuration document loaded from the FIRE configuration YAML file.
FIREConfigration is the primary configuration model for the FIRE application, serialized from and deserialized to YAML via YamlDotNet. It defines all the settings required to control the three-step file processing pipeline (collect, generate, execute).
Configuration Version: The configuration includes a ConfigurationVersion that must match SupportedConfigurationVersion (1.00). This ensures forward/backward compatibility and prevents accidental use of incompatible configuration files.
File Discovery and Storage: FilesRootPath lists the directory roots to scan for source files during the collect phase. DataBasePath and DataBaseFileName specify the location of the SQLite database file where records are persisted.
File Operations and Path Templates: Action specifies the file operation (Copy, Move, or Link). RootPath is the base directory for output files. SortingPatern and FileNamePatern are path templates containing placeholders like {Make}, {Model}, {DateTimeOriginal} that are resolved using collected metadata during the generate phase.
Text Substitution and Extension Overrides: StringReplacements defines global string replacements applied to all resolved paths. FileExtensions provides per-extension configuration overrides for specific file types, allowing different sorting patterns, keyword sets, and file operations for (e.g.) images vs. videos.
Deserialization and Normalization: The Parse and Load methods deserialize YAML using YamlDotNet. The Normalize method fills in defaults for all properties, ensuring predictable behavior even if some fields are omitted from the YAML file.
Loading and validating a configuration:
var config = FIREConfigration.Load("Configuration.yaml");
config.EnsureSupportedConfigurationVersion();
Console.WriteLine($"Root path: {config.RootPath}");
Console.WriteLine($"Sorting pattern: {config.SortingPatern}");
Console.WriteLine($"File extensions configured: {config.FileExtensions.Count}");
Definition at line 86 of file FIREConfigration.cs.
Member Function Documentation
EnsureSupportedConfigurationVersion()
void FIREConfigration::EnsureSupportedConfigurationVersion () inline
Throws an exception if the configuration version is not supported.
This method should be called after loading or parsing a configuration to ensure that the version is compatible with the current application build.
Exceptions
InvalidOperationException Thrown if ConfigurationVersion does not equal SupportedConfigurationVersion.
Definition at line 327 of file FIREConfigration.cs.
References IsConfigurationVersionSupported().
Referenced by ExecuteCollect(), ExecuteGenerate(), ExecuteInspect(), and ExecuteOperations().
IsConfigurationVersionSupported()
bool FIREConfigration::IsConfigurationVersionSupported ()
Checks whether the loaded configuration version matches the supported version.
Returns
true if the versions match; otherwise, false.
This is a non-throwing check. Use EnsureSupportedConfigurationVersion if you want an exception to be thrown on version mismatch.
References ConfigurationVersion, and SupportedConfigurationVersion.
Referenced by EnsureSupportedConfigurationVersion().
Load()
FIREConfigration FIREConfigration::Load (string filePath) inline static
Loads a FIRE configuration from a YAML file on disk.
Parameters
filePath The absolute or relative path to the configuration YAML file.
Returns
A deserialized and normalized FIREConfigration instance.
This method reads the entire file into memory, parses it, and returns a configuration instance. All properties are normalized to default values if missing from the file.
Exceptions
ArgumentException Thrown if filePath is null, empty, or whitespace.
FileNotFoundException Thrown if the specified file does not exist.
YamlException Thrown if the YAML file is malformed and cannot be parsed.
Definition at line 271 of file FIREConfigration.cs.
References Parse().
Referenced by ExecuteCollect(), ExecuteGenerate(), ExecuteInspect(), and ExecuteOperations().
Parse()
FIREConfigration FIREConfigration::Parse (string yaml) inline static
Parses YAML content into a FIREConfigration instance.
Parameters
yaml The YAML content string.
Returns
A deserialized and normalized FIREConfigration instance.
This method uses YamlDotNet's deserializer configured with null naming convention to map YAML properties exactly as written. Unknown properties are ignored. All properties are normalized to default values if missing.
Exceptions
ArgumentException Thrown if yaml is null, empty, or whitespace.
YamlException Thrown if the YAML content is malformed and cannot be parsed.
Definition at line 293 of file FIREConfigration.cs.
Referenced by Load().
Member Data Documentation
Action
string FIREConfigration::Action { get
Gets or sets the default file operation for all files (Copy, Move, or Link).
Valid values are "Copy", "Move", and "Link". This is the default action applied during the execute phase for files that do not have an extension-specific override in FileExtensions. Defaults to "Copy" if not specified.
Definition at line 152 of file FIREConfigration.cs.
ConfigurationVersion
decimal FIREConfigration::ConfigurationVersion { get
Gets or sets the configuration format version.
This value is loaded from the YAML field ConfigurationVersion. It must match SupportedConfigurationVersion or an exception will be thrown when EnsureSupportedConfigurationVersion is called.
Definition at line 106 of file FIREConfigration.cs.
Referenced by IsConfigurationVersionSupported().
DataBaseFileName
string FIREConfigration::DataBaseFileName { get
Gets or sets the name of the SQLite database file (e.g., "fire.db").
This is combined with DataBasePath to form the full database file path. If not specified in the configuration, it defaults to an empty string.
Definition at line 140 of file FIREConfigration.cs.
DataBasePath
string FIREConfigration::DataBasePath { get
Gets or sets the directory path where the SQLite database file is stored.
The complete database file path is constructed as Path.Combine(DataBasePath, DataBaseFileName). If DataBasePath is empty or null, the database file is created in the application's working directory.
Definition at line 130 of file FIREConfigration.cs.
FileExtensions
Dictionary<string, FileExtensionConfiguration> FIREConfigration::FileExtensions { get
Gets or sets a dictionary of file extension-specific configurations.
Keys are file extensions (e.g., ".jpg", ".mp4", ".raw") and values are FileExtensionConfiguration objects that override the root configuration for files with that extension. This allows different sorting patterns, keyword sets, and file operations for different file types. Case-insensitive comparison is used for keys.
Definition at line 224 of file FIREConfigration.cs.
FileNamePatern
string FIREConfigration::FileNamePatern { get
Gets or sets the file name pattern (may contain metadata placeholders).
This template defines the file name (without directory path) for output files. Placeholders are resolved similarly to SortingPatern. Example: {DateTimeOriginal:yyyy-MM-dd_HHmmss}_{Make}_{Model}
Definition at line 198 of file FIREConfigration.cs.
FileSorting
List<string> FIREConfigration::FileSorting { get
Gets or sets the ordered list of metadata keys used to sort records before path generation.
Each entry represents one sort criterion. Typical values are metadata keys such as Make, Model, or date-time component selectors like MetaCreationTime.Year, MetaCreationTime.Month, MetaCreationTime.Day.
The criteria are applied in the listed order (primary, secondary, tertiary, ...). If the list is empty, no explicit sorting is performed.
Definition at line 241 of file FIREConfigration.cs.
FileSortingOrder
string FIREConfigration::FileSortingOrder { get
Gets or sets the global sorting direction used for FileSorting.
Supported values are Ascending and Descending (case-insensitive). Defaults to Ascending.
Definition at line 251 of file FIREConfigration.cs.
FilesRootPath
List<string> FIREConfigration::FilesRootPath { get
Gets or sets the list of root directories to scan for source files during collection.
Each path in this list is recursively scanned to discover all qualifying files that match the configured file extension rules during the collect phase. Paths can use environment variables and relative paths; these should be resolved before passing to the file discovery logic.
Definition at line 118 of file FIREConfigration.cs.
MediaRootPath
string FIREConfigration::MediaRootPath { get
Gets or sets the media root path variable used in path templates.
This is a convenience placeholder that can be referenced in path templates as {MediaRootPath} to avoid hardcoding the base directory. Defaults to "CC" if not specified.
Definition at line 163 of file FIREConfigration.cs.
RootPath
string FIREConfigration::RootPath { get
Gets or sets the base root path for output directories (may contain placeholders).
This is a template that can reference other configuration placeholders (e.g., {MediaRootPath}). The template is resolved during the generate phase before being combined with the sorting and file name patterns. Defaults to "{MediaRootPath}" if not specified.
Definition at line 175 of file FIREConfigration.cs.
set
FIREConfigration::set
Definition at line 106 of file FIREConfigration.cs.
SortingPatern
string FIREConfigration::SortingPatern { get
Gets or sets the directory sorting path pattern (may contain metadata placeholders).
This is a template that defines the directory structure under RootPath. Placeholders like {Year}, {Make}, {CreationTime} are replaced with resolved metadata values during the generate phase. Example: {DateTimeOriginal:yyyy}/{DateTimeOriginal:MM}/{Make}
Definition at line 187 of file FIREConfigration.cs.
StringReplacements
Dictionary<string, string> FIREConfigration::StringReplacements { get
Gets or sets a dictionary of global string replacements applied to all resolved paths.
After all metadata placeholders are resolved and paths are constructed, each key in this dictionary is replaced with its corresponding value. This is useful for sanitizing or normalizing folder names (e.g., replacing spaces with underscores or removing invalid characters). Case-insensitive comparison is used for keys.
Definition at line 211 of file FIREConfigration.cs.
SupportedConfigurationVersion
const decimal FIREConfigration::SupportedConfigurationVersion = 1.10m
The semantic version of the configuration format currently supported by this build.
Configuration files must have ConfigurationVersion equal to this value. If the versions do not match, EnsureSupportedConfigurationVersion will throw.
Definition at line 95 of file FIREConfigration.cs.
Referenced by IsConfigurationVersionSupported().
The documentation for this class was generated from the following file:
FIRE/FIRE/FIREConfigration.cs