# Erstellt von Thomas Stoll am 2024-06-17
---
ConfigurationVersion: 1.30

FilesRootPath: 
  - D:\Media Originale\Automatic Upload
  # - S:\Mediengesamtsicherungen\Media\01 Mauritius Files 2024
  # - S:\Mediengesamtsicherungen\Media\0002
  # - S:\Mediengesamtsicherungen\Media\19.10.2017
  # - S:\Mediengesamtsicherungen\Media\28.09.2017
  # - S:\Mediengesamtsicherungen\Media\29.09.2017
  # - S:\Mediengesamtsicherungen\Media\30.09.2017
  # - S:\Mediengesamtsicherungen\Media\1904
DataBasePath: D:\Media\FIRE\FiReDatabase
DataBaseFileName: MediaDatabase.db

Action: Copy
MediaRootPath: S:\Media FIRE\Media
RootPath: "{MediaRootPath}"
SortingPatern: "{MediaRootPath}\\{MetaCreationTime.Year}\\{MetaCreationTime.Month}\\{MetaCreationTime.Day}\\{Make}\\{Model}"
FileNamePatern: "{MetaCreationTime.Year}-{MetaCreationTime.Month}-{MetaCreationTime.Day}_{Counter:D3}"

Logging:
  LogFilePath: S:\Media FIRE\Logs
  LogFileName: MediaFireLog.md
  LogLevel: Debug # Debug, Info, Warning, Error, Critical
  MaxFileSizeBytes: 10485760   # 10 MB
  MaxAgeDays: 30

StringReplacements:
  SM-G985F: SM-G985F Galaxy S20
  SM-S938B: SM-S938B Galaxy S25 Ultra
  SM-F766B: SM-F766B Galaxy Z Flip7
  SM-A528B: SM-A528B Galaxy A52s
  Galaxy Z Flip7: SM-F766B Galaxy Z Flip7
  Galaxy S25 Ultra: SM-S938B Galaxy S25 Ultra
  Sony XAVC: Sony
  "*IS0 14496*": DJI

FileSorting: 
- Model
- Make
- MetaCreationTime
FileSortingOrder: Ascending

FileExtensions:
  .jpg:
    FileType: Image 
    FileClass: RegularFile
    Action: Copy 
    RootPath: "{MediaRootPath}"
    SortingPatern: "{MediaRootPath}\\{MetaCreationTime.Year}\\{MetaCreationTime.Month}\\{MetaCreationTime.Day}\\{Make}\\{Model}"
    FileNamePatern: "{MetaCreationTime.Year}-{MetaCreationTime.Month}-{MetaCreationTime.Day}_{Counter:D3}.JPG"
    AvailableKeyWords:
      Make:
        DataType: STRING
        Source: EXIFTOOL
        SourceFields:
        - exififd:make
        - "DJI:Make"
        - "IFD0:Make"
      Model:
        DataType: STRING
        Source: EXIFTOOL
        SourceFields:
        - IFD0:Model
        - IFD0:UniqueCameraModel
      MetaCreationTime:
        DataType: DATETIME
        Source: EXIFTOOL
        Default: NOW
        ValAttribute: LOWEST
        SourceFields:
        - Composite:DateTimeCreated
        - Composite:SubSecCreateDate
        - ExifIFD:CreateDate
        - IPTC:DateCreated
        - IPTC:TimeCreated
        - XMP-photoshop:DateCreated
        - XMP-xmp:CreateDate
        - ExifIFD:DateTimeOriginal

  .png:
    FileType: Image
    FileClass: RegularFile
    Action: Copy
    RootPath: "{MediaRootPath}"
    SortingPatern: "{MediaRootPath}\\{MetaCreationTime.Year}\\{MetaCreationTime.Month}\\{MetaCreationTime.Day}\\{Make}\\{Model}"
    FileNamePatern: "{MetaCreationTime.Year}-{MetaCreationTime.Month}-{MetaCreationTime.Day}_{Counter:D3}.PNG"
    SidecarFileExtensions:
    - .xmp
    AvailableKeyWords:
      Make:
        DataType: STRING
        Source: EXIFTOOL
        SourceFields:
        - exififd:make
        - "DJI:Make"
        - "IFD0:Make"
      Model:
        DataType: STRING
        Source: EXIFTOOL
        SourceFields:
        - IFD0:Model
        - IFD0:UniqueCameraModel
      MetaCreationTime:
        DataType: DATETIME
        Source: EXIFTOOL
        ValAttribute: LOWEST
        Default: NOW
        SourceFields:
        - Composite:DateTimeCreated
        - Composite:SubSecCreateDate
        - ExifIFD:CreateDate
        - IPTC:DateCreated
        - IPTC:TimeCreated
        - XMP-photoshop:DateCreated
        - XMP-xmp:CreateDate

  .dng:
    FileType: Image # TODO: Enum for FileType and FileClass
    FileClass: RegularFile
    Action: Copy # todo: Enum for Action Move, Copy, Link
    RootPath: "{MediaRootPath}"
    SortingPatern: "{MediaRootPath}\\{MetaCreationTime.Year}\\{MetaCreationTime.Month}\\{MetaCreationTime.Day}\\{Make}\\{Model}"
    FileNamePatern: "{MetaCreationTime.Year}-{MetaCreationTime.Month}-{MetaCreationTime.Day}_{Counter:D3}.DNG"
    SidecarFileExtensions:
    - .xmp
    AvailableKeyWords:
      Make:
        DataType: STRING
        Source: EXIFTOOL
        SourceFields:
        - exififd:make
        - "DJI:Make"
        - "IFD0:Make"
      Model:
        DataType: STRING
        Source: EXIFTOOL
        SourceFields:
        - IFD0:Model
        - IFD0:UniqueCameraModel
      MetaCreationTime:
        DataType: DATETIME
        Source: EXIFTOOL
        ValAttribute: LOWEST
        Default: NOW
        SourceFields:
        - Composite:DateTimeCreated
        - Composite:SubSecCreateDate
        - ExifIFD:CreateDate
        - IPTC:DateCreated
        - IPTC:TimeCreated
        - XMP-photoshop:DateCreated
        - XMP-xmp:CreateDate

  .arw:
    FileType: Image # TODO: Enum for FileType and FileClass
    FileClass: RegularFile
    Action: Copy # todo: Enum for Action Move, Copy, Link
    RootPath: "{MediaRootPath}"
    SortingPatern: "{MediaRootPath}\\{MetaCreationTime.Year}\\{MetaCreationTime.Month}\\{MetaCreationTime.Day}\\{Make}\\{Model}"
    FileNamePatern: "{MetaCreationTime.Year}-{MetaCreationTime.Month}-{MetaCreationTime.Day}_{Counter:D3}.ARW"
    SidecarFileExtensions:
    - .xmp
    AvailableKeyWords:
      Make:
        DataType: STRING
        Source: EXIFTOOL
        SourceFields:
        - exififd:make
        - "DJI:Make"
        - "IFD0:Make"
      Model:
        DataType: STRING
        Source: EXIFTOOL
        SourceFields:
        - IFD0:Model
        - IFD0:UniqueCameraModel
      MetaCreationTime:
        DataType: DATETIME
        Source: EXIFTOOL
        ValAttribute: LOWEST
        Default: NOW
        SourceFields:
        - Composite:DateTimeCreated
        - Composite:SubSecCreateDate
        - ExifIFD:CreateDate
        - ExifIFD:DateTimeOriginal
        - IPTC:DateCreated
        - IPTC:TimeCreated
        - XMP-photoshop:DateCreated
        - XMP-xmp:CreateDate

  .mp4:
    FileType: Video
    FileClass: RegularFile
    Action: Copy
    RootPath: "{MediaRootPath}"
    SortingPatern: "{MediaRootPath}\\{MetaCreationTime.Year}\\{MetaCreationTime.Month}\\{MetaCreationTime.Day}\\{Make}\\{Model}"
    FileNamePatern: "{MetaCreationTime.Year}-{MetaCreationTime.Month}-{MetaCreationTime.Day}_{Counter:D3}.ARW"
    AvailableKeyWords:
      Make:
        DataType: STRING
        Source: EXIFTOOL
        Default: Samsung
        SourceFields:
        - QuickTime:MajorBrand
        - XML:DeviceManufacturer
      Model:
        DataType: STRING
        Source: EXIFTOOL
        Default: AnotherSamsungModel
        SourceFields:
        - Samsung:SamsungModel
        - XML:DeviceModelName
        - ItemList:Encoder
      MetaCreationTime:
        DataType: DATETIME
        Source: EXIFTOOL
        Default: NOW
        ValAttribute: LOWEST
        SourceFields:
        - QuickTime:CreateDate
        - Track1:TrackCreateDate
        - Track2:MediaCreateDate
