FIRE: FIRE/FIRE/FIREDatabase.cs File Reference
FIREDatabase.cs File Reference
Classes
class FIREFileMetaData
Represents a single metadata entry stored together with a database record.
class FIREStatusRecord
Represents the current status and state of the database content and recent persistence operations.
class FIREFileMetaDataEntity
Entity Framework Core entity class mapping to the FIREFileMetaDatas table.
class FIREDatabaseStatusEntity
Provides constant values and utility constants for the FIRE database status infrastructure.
Functions
FIREDatabase (string databaseFilePath, bool recreateIfExists=false)
Creates a new instance of FIREDatabase backed by the specified SQLite file.
void Reload ()
Reloads all file records from the SQLite database into the in-memory collection.
void RecreateDatabase ()
Recreates the SQLite database file from scratch.
void Save ()
Persists the current in-memory collection to the SQLite database.
void Add (FIREDbRecord item)
Adds a new record to the collection and persists the change immediately.
void Clear ()
Removes all records from the collection and persists the change immediately.
bool Contains (FIREDbRecord item)
Determines whether the specified record is present in the current collection.
void CopyTo (FIREDbRecord[] array, int arrayIndex)
Copies the in-memory collection to the specified array, starting at the specified index.
PersistCurrentState ("Updated", true, null)
int IndexOf (FIREDbRecord item)
Returns the zero-based index of the specified record in the collection.
void Insert (int index, FIREDbRecord item)
Inserts a record at the specified index and persists the change.
bool Remove (FIREDbRecord item)
Removes the specified record from the collection by value.
void RemoveAt (int index)
Removes the record at the specified index and persists the change.
void Dispose ()
Disposes the underlying Entity Framework Core database context.
IReadOnlyList< FIREDbRecord > AsReadOnlyList ()
Gets a read-only snapshot view of the current in-memory records.
IEnumerator< FIREDbRecord > GetEnumerator () => GetEnumerator()
Returns an enumerator that iterates through the records in the collection.
Variables
class FIREFileMetaData get = []
Represents one complete file record persisted in the FIRE database.
set
byte[] FileId { get
Gets or sets the binary file identifier from the NTFS file system, if available.
string SourceFilePath { get
Gets or sets the original source file path as discovered during the collect phase.
string TargetFilePath { get
Gets or sets the computed target file path, as determined during the generate phase.
List< FIREFileMetaData > FileMetaDatas { get
Gets or sets the file metadata entries associated with this record.
class FIREStatusRecord FIREDbRecord = []
Provides a list-like interface to FIREDbRecord file entries backed by a SQLite database.
class FIREStatusRecord _databaseFilePath = []
string DatabaseFilePath => _databaseFilePath
Gets the file path of the backing SQLite database.
FIREStatusRecord StatusRecord => _statusRecord
Gets the current persisted database status record.
int Count => _records.Count
Returns the number of records currently loaded in memory.
bool IsReadOnly => false
Gets a value indicating whether the collection is read-only.
FIREDbRecord this [int index]
Gets or sets the record at the specified index.
ulong VolumeSerialNumber { get
Gets or sets the volume serial number from the NTFS file system.
string Status { get
Gets or sets the status of the most recent operation.
bool Valid { get
Gets or sets a value indicating whether the stored data set is valid.
DateTime TimeStamp { get
Gets or sets the UTC timestamp of the most recent status change.
string ErrorMessage { get
Gets or sets the error message, if the last operation failed.
Class Documentation
FIREFileMetaData
class FIREFileMetaData
Represents a single metadata entry stored together with a database record.
Each FIREFileMetaData instance encapsulates a key-value pair extracted from a file, along with metadata about the value's type and source origin. Multiple metadata entries are grouped into a single FIREDbRecord.
This class is used as a domain model in the FIRE library. It is persisted to the SQLite database via Entity Framework Core and mapped to/from the internal FIREFileMetaDataEntity class.
Typical metadata keys include:
Make, Model (camera information from EXIF)
DateTimeOriginal, DateTimeDigitized (from EXIF)
CreationTime, ModificationTime (from file system)
Custom keyword names resolved from configuration
The DataSource value typically indicates which IMetadataSource provided the entry (e.g., "EXIFTOOL", "FILEINFO").
Creating and populating metadata entries:
var metadata = new FIREFileMetaData
{
    Key = "Make",
    Value = "Apple",
    TypeName = typeof(string).FullName,
    DataSource = "EXIFTOOL"
};
Definition at line 65 of file FIREDatabase.cs.
Class Members
string DataSource { get Gets or sets the source of the metadata value.
Valid values include "EXIFTOOL" (extracted via ExifTool) and "FILEINFO" (extracted from the file system). This field is useful for auditing and debugging the metadata collection process.
long Id { get Gets or sets the database identifier (primary key) of the metadata row.
This is auto-generated by the SQLite database when the row is inserted. Typically, you do not set this value manually; it is managed by Entity Framework Core.
string Key { get Gets or sets the metadata key name.
Examples: "Make", "Model", "DateTimeOriginal", "CreationTime". This key corresponds to the keyword name defined in the FIRE configuration.
set
string TypeName { get Gets or sets the CLR type name of the logical value.
This is the fully qualified name of the original .NET type, such as "System.String", "System.Int32", "System.DateTime". It is recorded to support type-aware parsing and formatting when the value is used in template placeholders.
string Value { get Gets or sets the metadata value as a string.
All metadata values are stored as strings, regardless of their logical type. The logical type is recorded separately in the TypeName property. For example, an integer resolution value might be stored as "300" with TypeName set to "System.Int32".
FIREStatusRecord
class FIREStatusRecord
Represents the current status and state of the database content and recent persistence operations.
There is exactly one FIREStatusRecord row in the database at all times (with Id equal to 1). It is created during FIREDatabase initialization and is updated after every persistence operation (Save, Add, Clear, etc.).
The status indicates the result of the most recent operation:
Initialized – Database was just created
Saved – Last operation completed successfully
Failed – The last operation encountered an error
Saving – Operation in progress (rarely observed)
The Valid field indicates whether the stored data set is consistent and complete. It is set to false when an error occurs during persistence. The ErrorMessage field captures the exception message if Valid is false.
Checking the database status after a batch operation:
var status = database.StatusRecord;
if (!status.Valid)
{
    Console.WriteLine($"Error: {status.ErrorMessage}");
}
else
{
    Console.WriteLine($"Last operation: {status.Status} at {status.TimeStamp:O}");
}
Definition at line 261 of file FIREDatabase.cs.
Class Members
string ErrorMessage { get Gets or sets an optional error message for failed operations.
This field is populated only if Valid is false. It contains the Message of the exception that was caught during the most recent persistence operation.
long Id { get Gets or sets the database identifier (primary key) of the status row.
This is always 1 (see FIREDatabaseStatusEntity.SingletonId) to enforce the singleton pattern. Only one status row exists in the database.
set
string Status { get Gets or sets a textual status value describing the result of the most recent operation.
Typical values: "Ready", "Saving", "Saved", "Completed", "Failed", "Initialized", "Cleared". This status is updated immediately before and after each persistence operation.
DateTime TimeStamp { get Gets or sets the UTC timestamp when the status was last changed.
This timestamp is updated after every persistence operation and is useful for auditing and monitoring the database activity timeline.
bool Valid { get Gets or sets a value indicating whether the stored data set is valid and complete.
This is true if the most recent operation succeeded. If an exception occurs during persistence, this is set to false and ErrorMessage is populated. Can be used as a quick health check for the database state.
FIREFileMetaDataEntity
class FIREFileMetaDataEntity
Entity Framework Core entity class mapping to the FIREFileMetaDatas table.
This is an internal EF Core entity-mapped class used only within the data persistence layer. It corresponds to the domain model FIREFileMetaData. The Record navigation property represents the one-to-many relationship with FIREDbRecordEntity.
Definition at line 1004 of file FIREDatabase.cs.
Class Members
string DataSource { get Gets or sets the source of the metadata value.
long Id { get Gets or sets the auto-generated database identifier (primary key).
string Key { get Gets or sets the metadata key.
FIREDbRecordEntity Record { get Gets or sets the parent file record (navigation property).
This navigation property is used by EF Core to establish the relationship between metadata entries and their parent record. In normal operation, you should not need to access this property directly; instead, work with the FIREDbRecord.FileMetaDatas collection from the record side.
long RecordId { get Gets or sets the foreign key to the parent file record.
This property links this metadata entry to its parent file record. It is required for maintaining the one-to-many relationship.
set
string TypeName { get Gets or sets the CLR type name of the logical value.
string Value { get Gets or sets the metadata value as a string.
FIREDatabaseStatusEntity
class FIREDatabaseStatusEntity
Provides constant values and utility constants for the FIRE database status infrastructure.
This static class contains configuration constants for the database status singleton. Currently, it defines the constant primary key ID for the status row, ensuring that exactly one status record exists in the database at all times.
Definition at line 1101 of file FIREDatabase.cs.
Class Members
const long SingletonId = 1 The singleton primary key value for the status record (always 1).
There is exactly one status record in the database, and its ID is always 1. This constant is used throughout the persistence layer to query, update, and retrieve the status record.
Function Documentation
Add()
void Add (FIREDbRecord item)
Adds a new record to the collection and persists the change immediately.
Parameters
item The FIREDbRecord to add.
The record is added to the in-memory list and immediately persisted to the database via a PersistCurrentState call. After persistence, the entire collection is reloaded from the database to ensure consistency.
Exceptions
ArgumentNullException Thrown if item is null.
ObjectDisposedException Thrown if this instance has been disposed.
Definition at line 533 of file FIREDatabase.cs.
References FIREDbRecord, PersistCurrentState(), and Reload().
AsReadOnlyList()
IReadOnlyList< FIREDbRecord > AsReadOnlyList ()
Gets a read-only snapshot view of the current in-memory records.
Returns
A IReadOnlyList<T> containing the current records.
The returned collection is a snapshot at the time of the call and does not reflect subsequent modifications to the database.
Clear()
void Clear ()
Removes all records from the collection and persists the change immediately.
This method clears the in-memory list, persists the empty state to the database, and reloads. After this call, the database contains no file records.
Exceptions
ObjectDisposedException Thrown if this instance has been disposed.
Definition at line 553 of file FIREDatabase.cs.
References PersistCurrentState(), and Reload().
Contains()
bool Contains (FIREDbRecord item)
Determines whether the specified record is present in the current collection.
Parameters
item The record to locate.
Returns
true if the record is in the collection; otherwise, false.
References FIREDbRecord.
CopyTo()
void CopyTo (FIREDbRecord[] array, int arrayIndex)
Copies the in-memory collection to the specified array, starting at the specified index.
Parameters
array The destination array.
arrayIndex The zero-based index in the array where copying begins.
References FIREDbRecord.
Dispose()
void Dispose ()
Disposes the underlying Entity Framework Core database context.
After calling this method, all operations on this instance will throw ObjectDisposedException. This method is safe to call multiple times.
Definition at line 703 of file FIREDatabase.cs.
FIREDatabase()
FIREDatabase (string databaseFilePath, bool recreateIfExists = false)
Creates a new instance of FIREDatabase backed by the specified SQLite file.
Parameters
databaseFilePath Full path to the SQLite database file. If the directory does not exist, it is created. If recreateIfExists is true and the file exists, it will be deleted.
recreateIfExists If true, any existing database file is deleted and recreated from scratch. If false (the default), an existing database is reused.
Exceptions
ArgumentException Thrown if databaseFilePath is null, empty, or whitespace.
IOException Thrown if the directory cannot be created or the database file cannot be accessed.
Definition at line 402 of file FIREDatabase.cs.
References _databaseFilePath, and Reload().
Referenced by ExecuteCollect(), ExecuteGenerate(), ExecuteOperations(), and FIRECatalog().
GetEnumerator()
IEnumerator IEnumerable GetEnumerator () => GetEnumerator()
Returns an enumerator that iterates through the records in the collection.
IndexOf()
int IndexOf (FIREDbRecord item)
Returns the zero-based index of the specified record in the collection.
Parameters
item The record to locate.
Returns
The index of the record, or -1 if it is not found.
References FIREDbRecord.
Insert()
void Insert (int index, FIREDbRecord item)
Inserts a record at the specified index and persists the change.
Parameters
index The zero-based index at which the record should be inserted.
item The record to insert.
The record is inserted into the in-memory list at the specified position, then persisted to the database immediately via PersistCurrentState and reloaded.
Exceptions
ArgumentNullException Thrown if item is null.
ObjectDisposedException Thrown if this instance has been disposed.
Definition at line 639 of file FIREDatabase.cs.
References FIREDbRecord, PersistCurrentState(), and Reload().
PersistCurrentState()
PersistCurrentState ("Updated" , true , null)
Referenced by Add(), Clear(), Insert(), RecreateDatabase(), Remove(), RemoveAt(), and Save().
RecreateDatabase()
void RecreateDatabase ()
Recreates the SQLite database file from scratch.
This method deletes the entire database, recreates it with all schema tables, and initializes the singleton status row. All in-memory records are cleared, and the status is updated to "Recreated".
Exceptions
ObjectDisposedException Thrown if this instance has been disposed.
Definition at line 484 of file FIREDatabase.cs.
References PersistCurrentState(), and Reload().
Reload()
Reload ()
Reloads all file records from the SQLite database into the in-memory collection.
This method clears the current in-memory list and repopulates it from the database. It also reloads the singleton status record. Use this method to sync in-memory state with the database after an external modification (e.g., another process updating the file).
Exceptions
ObjectDisposedException Thrown if this instance has been disposed.
Definition at line 455 of file FIREDatabase.cs.
References FIREDatabaseStatusEntity::SingletonId.
Referenced by Add(), Clear(), FIREDatabase(), Insert(), RecreateDatabase(), Remove(), RemoveAt(), and Save().
Remove()
bool Remove (FIREDbRecord item)
Removes the specified record from the collection by value.
Parameters
item The record to remove.
Returns
true if the record was found and removed; otherwise, false.
If the record is found, it is removed from the in-memory list and the change is persisted to the database immediately. If the record is not found, no change is made and false is returned.
Exceptions
ObjectDisposedException Thrown if this instance has been disposed.
Definition at line 662 of file FIREDatabase.cs.
References FIREDbRecord, PersistCurrentState(), and Reload().
RemoveAt()
void RemoveAt (int index)
Removes the record at the specified index and persists the change.
Parameters
index The zero-based index of the record to remove.
The record at the specified index is removed from the in-memory list and the change is persisted to the database immediately.
Exceptions
ObjectDisposedException Thrown if this instance has been disposed.
Definition at line 687 of file FIREDatabase.cs.
References PersistCurrentState(), and Reload().
Save()
void Save ()
Persists the current in-memory collection to the SQLite database.
This method replaces all records in the database with the current in-memory collection and updates the status to "Saved". The operation is wrapped in a database transaction for atomicity.
Exceptions
ObjectDisposedException Thrown if this instance has been disposed.
Exception If the persistence operation fails, the status record is updated to "Failed" with the error message, and the exception is rethrown.
Definition at line 511 of file FIREDatabase.cs.
References PersistCurrentState(), and Reload().
Variable Documentation
_databaseFilePath
class FIREStatusRecord _databaseFilePath = []
Referenced by FIREDatabase().
Count
int Count => _records.Count
Returns the number of records currently loaded in memory.
Definition at line 579 of file FIREDatabase.cs.
DatabaseFilePath
string DatabaseFilePath => _databaseFilePath
Gets the file path of the backing SQLite database.
Definition at line 432 of file FIREDatabase.cs.
ErrorMessage
string ErrorMessage { get
Gets or sets the error message, if the last operation failed.
Definition at line 1090 of file FIREDatabase.cs.
FileId
byte [] FileId { get
Gets or sets the binary file identifier from the NTFS file system, if available.
Gets or sets the binary file identifier from the NTFS file system.
This 16-byte identifier is unique per file on the NTFS volume and persists even if the file is renamed or moved. It is obtained via the Windows API's GetFileInformationByHandleEx function. This field is null on non-NTFS systems or if the API call fails.
File IDs are useful for detecting hard links to the same physical file, which is important for avoiding duplicate processing.
Definition at line 188 of file FIREDatabase.cs.
FileMetaDatas
List< FIREFileMetaDataEntity > FileMetaDatas { get
Gets or sets the file metadata entries associated with this record.
Gets or sets the collection of file metadata entries associated with this record.
This collection is populated during the collect phase by querying all configured metadata sources (EXIFTOOL, FILEINFO, etc.) for the file. The collection is persisted to the database as child rows in a one-to-many relationship. Each entry in this list corresponds to a single keyword resolved from the FIRE configuration.
This is a navigation property used by EF Core for lazy-loading and cascade deletes. When a record is deleted, all associated metadata entries are also deleted due to the Cascade delete behavior configured in FIREDatabaseContext.OnModelCreating(ModelBuilder).
Definition at line 224 of file FIREDatabase.cs.
FIREDbRecord
class FIREStatusRecord FIREDbRecord = []
Provides a list-like interface to FIREDbRecord file entries backed by a SQLite database.
FIREDatabase combines Entity Framework Core with SQLite persistence to provide a simple in-memory collection abstraction over stored file records. It implements the IList<T> interface, allowing standard collection operations while automatically persisting changes to the database.
Architecture: The class maintains an in-memory _records list and a FIREDatabaseContext for EF Core operations. When you modify the collection (Add, Remove, Clear, etc.), the changes are immediately persisted to the underlying SQLite database via PersistCurrentState, which wraps the entire operation in a transaction.
Initialization: When you create a new instance, the SQLite file is created if it doesn't exist. If recreateIfExists is true, any existing database is deleted first. A singleton status row is automatically initialized to track database state.
Reload and Persistence: The Reload method reloads all records from the database into memory. The Save method persists the current in-memory list to the database. Every modification operation (Add, Remove, etc.) automatically calls PersistCurrentState to flush changes to the database immediately.
Status Tracking: The StatusRecord property provides access to the singleton status row, which records the result and timestamp of the most recent operation. If a persistence operation fails, the status is set to "Failed" and the error message is recorded.
Thread Safety: This class is not inherently thread-safe. Multiple concurrent modifications to the same database from different threads or processes will likely result in conflicts. Ensure external synchronization if concurrent access is required.
Creating a database and adding records:
using var db = new FIREDatabase("D:\\data\\fire.db", recreateIfExists: true);
var record = new FIREDbRecord
{
    SourceFilePath = @"D:\Photos\IMG_1234.jpg",
    FileMetaDatas = new List<FIREFileMetaData>
    {
        new() { Key = "Make", Value = "Nikon" }
    }
};
db.Add(record);
Console.WriteLine($"Total records: {db.Count}");
Console.WriteLine($"Status: {db.StatusRecord.Status}");
Referenced by Add(), Contains(), CopyTo(), IndexOf(), Insert(), and Remove().
get
internal sealed class FIREFileMetaDataEntity get = []
Represents one complete file record persisted in the FIRE database.
Entity Framework Core entity class mapping to the FIREStatusRecord table.
Entity Framework Core entity class mapping to the FIREDbRecords table.
Each FIREDbRecord corresponds to a single source file that has been scanned and catalogued by the FIRE pipeline. It stores file identification information, paths, and all metadata collected from the file.
A FIREDbRecord is the primary domain model for FIRE. It typically progresses through the three-step pipeline as follows:
collect: SourceFilePath is set, and FileMetaDatas are populated from configured metadata sources.
generate: TargetFilePath is computed by evaluating path templates with resolved metadata values.
execute: The file operation (Copy, Move, or Link) is performed from SourceFilePath to TargetFilePath.
The VolumeSerialNumber and FileId are used on Windows/NTFS systems to detect hard links and duplicates, avoiding unnecessary processing of the same physical file.
Creating a record after file collection:
var record = new FIREDbRecord
{
    SourceFilePath = @"D:\Photos\IMG_1234.jpg",
    VolumeSerialNumber = volumeSerialNumber,
    FileId = fileId,
    FileMetaDatas = new List<FIREFileMetaData>
    {
        new() { Key = "Make", Value = "Apple", DataSource = "EXIFTOOL" },
        new() { Key = "Model", Value = "iPhone 15 Pro", DataSource = "EXIFTOOL" }
    }
};
Gets or sets the volume serial number of the NTFS volume where the source file resides.
This is obtained via Windows API calls and is used to detect files on the same physical volume. On non-Windows systems, this field may remain zero. Used by FIRE to identify and potentially skip duplicate files on the same volume.
This is an internal EF Core entity-mapped class used only within the data persistence layer. It is not exposed in the public API; instead, the domain model FIREDbRecord is used. This class includes navigation properties for Entity Framework's lazy-loading and change-tracking capabilities.
Gets or sets the auto-generated database identifier (primary key).
This is an internal EF Core entity-mapped class used only within the data persistence layer. It corresponds to the domain model FIREStatusRecord. There is exactly one row in this table (with Id = 1) that tracks the status of the most recent database operation.
Gets or sets the database identifier (primary key).
This is always 1 (see FIREDatabaseStatusEntity.SingletonId) to enforce the singleton pattern.
IsReadOnly
bool IsReadOnly => false
Gets a value indicating whether the collection is read-only.
This property always returns false because changes to the collection are allowed and are persisted to the database.
Definition at line 588 of file FIREDatabase.cs.
set
set
Initial value:
{
            ThrowIfDisposed()
Definition at line 174 of file FIREDatabase.cs.
SourceFilePath
string SourceFilePath { get
Gets or sets the original source file path as discovered during the collect phase.
Gets or sets the original source file path.
This is the absolute path to the source file before any file operation is performed. It is populated during the collect phase and should not be modified thereafter.
Example: D:\Photos\Import\IMG_1234.jpg
Definition at line 199 of file FIREDatabase.cs.
Status
string Status { get
Gets or sets the status of the most recent operation.
Definition at line 1075 of file FIREDatabase.cs.
StatusRecord
FIREStatusRecord StatusRecord => _statusRecord
Gets the current persisted database status record.
This property returns a reference to the singleton status row that is updated after every persistence operation. Inspect this record to check the result of the last operation and any error messages.
Definition at line 442 of file FIREDatabase.cs.
TargetFilePath
string TargetFilePath { get
Gets or sets the computed target file path, as determined during the generate phase.
Gets or sets the computed target file path.
This path is calculated by evaluating the SortingPatern and FileNamePatern configuration templates with resolved metadata values. It is set to null initially and is populated during the generate phase. It is then used during the execute phase to perform the actual file operation (Copy, Move, or Link).
Example: D:\Photos\Sorted\2026\07\Apple iPhone 15 Pro\2026-07-04_IMG_1234.jpg
Definition at line 212 of file FIREDatabase.cs.
this
FIREDbRecord this[int index]
Initial value:
{
        get => _records[index]
Gets or sets the record at the specified index.
Parameters
index The zero-based index of the record to get or set.
Returns
The record at the specified index.
Setting a value at an index persists the change immediately to the database via a PersistCurrentState call and then reloads the collection.
Exceptions
ArgumentNullException Thrown when attempting to set a null value at an index.
ObjectDisposedException Thrown if this instance has been disposed.
Definition at line 605 of file FIREDatabase.cs.
TimeStamp
DateTime TimeStamp { get
Gets or sets the UTC timestamp of the most recent status change.
Definition at line 1085 of file FIREDatabase.cs.
Valid
bool Valid { get
Gets or sets a value indicating whether the stored data set is valid.
Definition at line 1080 of file FIREDatabase.cs.
VolumeSerialNumber
ulong VolumeSerialNumber { get
Gets or sets the volume serial number from the NTFS file system.
This is stored as a long (int64) in the database and converted to/from the ulong (uint64) property via EF Core's value converters.
Definition at line 967 of file FIREDatabase.cs.