FIRE: UnitTest1 Class Reference
UnitTest1 Class Reference
Public Member Functions
void ApplyStringReplacement_ExactPattern_ReplacesOnlyMatchingSubstring ()
void ApplyStringReplacement_WildcardPattern_ReplacesMatchedSegment ()
void ApplyStringReplacement_RegexPrefix_UsesRegexReplacement ()
void ResolveKeywordDefaultValue_DatetimeNow_UsesProvidedNowValueAndNormalizes ()
void ResolveKeywordDefaultValue_DatetimeString_NormalizesToDatabaseFormat ()
void ResolveKeywordDefaultValue_InvalidDatetimeDefault_ReturnsNA ()
void ResolveKeywordDefaultValue_StringDefault_ReturnsDefaultUnchanged ()
void ParseTemplate_DatetimeKeywordSupport_ResolvesNamedAndFormatSuffixes ()
void ParseTemplate_NonDatetimeKeywordWithSuffix_DoesNotApplyDateFallback ()
Detailed Description
Definition at line 8 of file UnitTest1.cs.
Member Function Documentation
ApplyStringReplacement_ExactPattern_ReplacesOnlyMatchingSubstring()
void UnitTest1::ApplyStringReplacement_ExactPattern_ReplacesOnlyMatchingSubstring () inline
Definition at line 11 of file UnitTest1.cs.
References FIRECatalog().
ApplyStringReplacement_RegexPrefix_UsesRegexReplacement()
void UnitTest1::ApplyStringReplacement_RegexPrefix_UsesRegexReplacement () inline
Definition at line 29 of file UnitTest1.cs.
References FIRECatalog().
ApplyStringReplacement_WildcardPattern_ReplacesMatchedSegment()
void UnitTest1::ApplyStringReplacement_WildcardPattern_ReplacesMatchedSegment () inline
Definition at line 20 of file UnitTest1.cs.
References FIRECatalog().
ParseTemplate_DatetimeKeywordSupport_ResolvesNamedAndFormatSuffixes()
void UnitTest1::ParseTemplate_DatetimeKeywordSupport_ResolvesNamedAndFormatSuffixes () inline
Definition at line 99 of file UnitTest1.cs.
ParseTemplate_NonDatetimeKeywordWithSuffix_DoesNotApplyDateFallback()
void UnitTest1::ParseTemplate_NonDatetimeKeywordWithSuffix_DoesNotApplyDateFallback () inline
Definition at line 117 of file UnitTest1.cs.
ResolveKeywordDefaultValue_DatetimeNow_UsesProvidedNowValueAndNormalizes()
void UnitTest1::ResolveKeywordDefaultValue_DatetimeNow_UsesProvidedNowValueAndNormalizes () inline
Definition at line 38 of file UnitTest1.cs.
References DataType, and Default.
ResolveKeywordDefaultValue_DatetimeString_NormalizesToDatabaseFormat()
void UnitTest1::ResolveKeywordDefaultValue_DatetimeString_NormalizesToDatabaseFormat () inline
Definition at line 54 of file UnitTest1.cs.
References DataType, and Default.
ResolveKeywordDefaultValue_InvalidDatetimeDefault_ReturnsNA()
void UnitTest1::ResolveKeywordDefaultValue_InvalidDatetimeDefault_ReturnsNA () inline
Definition at line 69 of file UnitTest1.cs.
References DataType, and Default.
ResolveKeywordDefaultValue_StringDefault_ReturnsDefaultUnchanged()
void UnitTest1::ResolveKeywordDefaultValue_StringDefault_ReturnsDefaultUnchanged () inline
Definition at line 84 of file UnitTest1.cs.
References DataType, and Default.
The documentation for this class was generated from the following file:
FIRE/FIRE.Tests/UnitTest1.cs