FIRE: FIRE/FIRE/FIRECatalog.cs File Reference
FIRECatalog.cs File Reference
Classes
class FileInfoMetadataSource
Metadata source that extracts file system properties (timestamps).
class MetadataSourceRegistry
Registry for registered metadata sources.
struct FILE_ID_INFO
Marshalled structure for retrieving file ID information from Windows NTFS.
Enumerations
enum FileInfoByHandleClass
Functions
enum FileInfoByHandleClass ExtractMetadata (string filePath)
Extracts all available metadata from the specified file using ExifTool.
ExifToolMetadataSource ()
Initializes a new instance of ExifToolMetadataSource.
void Dispose ()
Disposes the underlying ExifTool instance.
sealed class MetadataSourceRegistry DllImport ("kernel32.dll", SetLastError=true)] private static extern bool GetFileInformationByHandle(SafeFileHandle hFile
Orchestrates the three-step FIRE processing pipeline: collect, generate, and execute.
MetadataSourceRegistry ()
Initializes a new instance of MetadataSourceRegistry.
void Register (IMetadataSource source)
Registers or replaces a metadata source in the registry.
IMetadataSource GetSource (string sourceName)
Retrieves a registered metadata source by name.
FIRECatalog (FIREConfigration configuration, FIREDatabase database)
Initializes a new instance of FIRECatalog.
void CollectFiles (Action< string >? progressCallback=null)
Step 1: Collects all files and their metadata from configured root directories.
void GenerateTargetPaths (Action< string >? progressCallback=null)
Step 2: Generates target file paths for all collected file records.
void ExecuteFileOperations (Action< string >? progressCallback=null)
Step 3: Executes the configured file operation (Copy, Move, or Link) for all records.
Variables
enum FileInfoByHandleClass string
Defines an abstraction for metadata extraction from files.
FileBasicInfo = 0
FileStandardInfo = 1
FileNameInfo = 2
FileRenameInfo = 3
FileDispositionInfo = 4
FileAllocationInfo = 5
FileEndOfFileInfo = 6
FileStreamInfo = 7
FileCompressionInfo = 8
FileAttributeTagInfo = 9
FileIdBothDirectoryInfo = 10
FileIdBothDirectoryRestartInfo = 11
FileIoPriorityHintInfo = 12
FileRemoteProtocolInfo = 13
FileFullDirectoryInfo = 14
FileFullDirectoryRestartInfo = 15
FileStorageInfo = 16
FileAlignmentInfo = 17
FileIdInfo = 18
FileIdExtdDirectoryInfo = 19
FileIdExtdDirectoryRestartInfo = 20
MaximumFileInfoByHandleClass
string SourceName { get
Gets the name of the metadata source.
FileInfoMetadataSource IMetadataSource
Metadata source for extracting embedded file metadata using ExifTool.
FileInfoMetadataSource _exifTool
sealed class MetadataSourceRegistry out BY_HANDLE_FILE_INFORMATION lpFileInformation
struct FILE_ID_INFO FileAttributes
System Runtime InteropServices ComTypes FILETIME CreationTime
System Runtime InteropServices ComTypes FILETIME LastAccessTime
System Runtime InteropServices ComTypes FILETIME LastWriteTime
uint VolumeSerialNumber
uint FileSizeHigh
uint FileSizeLow
uint NumberOfLinks
uint FileIndexHigh
uint FileIndexLow
Class Documentation
FILE_ID_INFO
struct FILE_ID_INFO
Marshalled structure for retrieving file ID information from Windows NTFS.
This structure receives output from the Windows API call GetFileInformationByHandleEx with FileInfoByHandleClass.FileIdInfo, and contains the volume serial number and file ID.
Definition at line 494 of file FIRECatalog.cs.
Class Members
byte[] FileId The 16-byte file identifier, unique per file on the NTFS volume.
ulong VolumeSerialNumber The volume serial number where the file resides.
Enumeration Type Documentation
FileInfoByHandleClass
enum FileInfoByHandleClass
Definition at line 34 of file FIRECatalog.cs.
Function Documentation
CollectFiles()
void CollectFiles (Action< string >? progressCallback = null)
Step 1: Collects all files and their metadata from configured root directories.
Parameters
progressCallback Optional callback invoked for each file being processed. The callback receives the file path. Use this to report progress in a UI or log file.
This method:
Clears any existing records from the database.
Recursively scans all paths in FIREConfigration.FilesRootPath.
For each file matching a configured file extension:
Retrieves file ID information from the OS.
Queries metadata from all configured sources and keywords.
Creates a FIREDbRecord and adds it to the database.
Saves all records to the database when complete.
Errors during file access or metadata extraction are logged but do not stop the pipeline.
Exceptions
ObjectDisposedException Thrown if this instance has been disposed.
Definition at line 603 of file FIRECatalog.cs.
References Action.
Dispose()
void Dispose ()
Disposes the underlying ExifTool instance.
Disposes the database and metadata sources held by this instance.
This method is safe to call multiple times. After calling this method, further calls to ExtractMetadata will fail silently or throw an exception.
This method is safe to call multiple times. After calling this method, all other methods will throw ObjectDisposedException.
Definition at line 309 of file FIRECatalog.cs.
References _exifTool.
DllImport()
sealed class MetadataSourceRegistry DllImport ("kernel32.dll" , SetLastError = true)
Orchestrates the three-step FIRE processing pipeline: collect, generate, and execute.
FIRECatalog is the main orchestrator that drives metadata collection from files, generates target directory and file names using path templates, and executes file operations (Copy, Move, or Link). It integrates the configuration, database, and metadata sources to implement the complete file processing workflow.
Three-Step Workflow:
Collect: CollectFiles recursively scans all configured root directories, creates file records for each file, and populates metadata from configured sources.
Generate: GenerateTargetPaths computes output directory and file name for each record by parsing path templates with resolved metadata values.
Execute: ExecuteFileOperations performs the configured file operation (Copy, Move, or Link) from source to target path.
Windows File Identification: FIRECatalog uses Windows API calls (GetFileInformationByHandleEx) to retrieve volume serial numbers and file IDs, which enable detection of hard links and files on the same physical volume. This is done on Windows/NTFS systems only.
Extensibility: The metadata extraction system is extensible via MetadataSourceRegistry. Custom metadata sources can be registered to support additional file formats or sources.
Resource Management: This class implements IDisposable to properly clean up the database and metadata sources. Always dispose of this instance when done.
Using FIRECatalog for the complete pipeline:
var config = FIREConfigration.Load("Configuration.yaml");
config.EnsureSupportedConfigurationVersion();
var dbPath = Path.Combine(config.DataBasePath, config.DataBaseFileName);
using var database = new FIREDatabase(dbPath);
using (var catalog = new FIRECatalog(config, database))
{
    // Step 1: Collect metadata
    catalog.CollectFiles(path => Console.WriteLine($"Collecting: {path}"));
    // Step 2: Generate target paths
    catalog.GenerateTargetPaths(path => Console.WriteLine($"Generating: {path}"));
    // Step 3: Execute file operations
    catalog.ExecuteFileOperations(path => Console.WriteLine($"Processing: {path}"));
}
References MetadataSourceRegistry::MetadataSourceRegistry().
ExecuteFileOperations()
void ExecuteFileOperations (Action< string >? progressCallback = null)
Step 3: Executes the configured file operation (Copy, Move, or Link) for all records.
Parameters
progressCallback Optional callback invoked for each file being processed. The callback receives the file path.
This method iterates over all records and performs the configured file operation:
Skips records with null or invalid paths or files that no longer exist.
Looks up the file extension configuration.
Retrieves the action (Copy, Move, or Link) using extension-specific overrides if available.
Calls ExecuteAction to perform the operation.
The operation creates all necessary output directories and handles errors gracefully. All changes are persisted to the database when complete.
Exceptions
ObjectDisposedException Thrown if this instance has been disposed.
Definition at line 698 of file FIRECatalog.cs.
References Action.
ExifToolMetadataSource()
ExifToolMetadataSource ()
Initializes a new instance of ExifToolMetadataSource.
This creates a new SharpExifTool.ExifTool instance that is used for all subsequent metadata extractions. The instance is disposed when this source is disposed.
Definition at line 252 of file FIRECatalog.cs.
References _exifTool.
Referenced by MetadataSourceRegistry::MetadataSourceRegistry().
ExtractMetadata()
Dictionary< string, string > ExtractMetadata (string filePath)
Extracts all available metadata from the specified file using ExifTool.
Parameters
filePath Absolute path to the file.
Returns
A dictionary containing all extracted metadata key-value pairs, or an empty dictionary if the file does not exist, ExifTool is unavailable, or extraction fails.
ExifTool is called synchronously via GetAwaiter().GetResult() to support the synchronous interface. This may block briefly while ExifTool processes the file.
Definition at line 269 of file FIRECatalog.cs.
References _exifTool.
FIRECatalog()
FIRECatalog (FIREConfigration configuration, FIREDatabase database)
Initializes a new instance of FIRECatalog.
Parameters
configuration The FIRE configuration containing paths, patterns, and keyword definitions.
database The database instance for persisting file records and metadata.
Exceptions
ArgumentNullException Thrown if configuration or database is null.
Definition at line 530 of file FIRECatalog.cs.
References FIREDatabase(), and MetadataSourceRegistry().
Referenced by ExecuteCollect(), ExecuteGenerate(), and ExecuteOperations().
GenerateTargetPaths()
void GenerateTargetPaths (Action< string >? progressCallback = null)
Step 2: Generates target file paths for all collected file records.
Parameters
progressCallback Optional callback invoked for each file being processed. The callback receives the file path.
This method iterates over all records in the database and computes the target directory and file name by:
Looking up the file extension configuration.
Retrieving the sorting and file name patterns (using extension-specific overrides if available).
Resolving metadata placeholders in the patterns using ParseTemplate.
Applying global string replacements from the configuration.
Constructing the final target path.
The target path is set in the FIREDbRecord.TargetFilePath property. If the patterns or resolution fails, the target path remains null.
Exceptions
ObjectDisposedException Thrown if this instance has been disposed.
Definition at line 643 of file FIRECatalog.cs.
References Action.
GetSource()
IMetadataSource DllImport::GetSource (string sourceName)
Retrieves a registered metadata source by name.
Parameters
sourceName The name of the source (case-insensitive).
Returns
The registered IMetadataSource with the specified name, or null if no source with that name is registered.
Definition at line 34 of file FIRECatalog.cs.
MetadataSourceRegistry()
DllImport::MetadataSourceRegistry ()
Initializes a new instance of MetadataSourceRegistry.
The constructor automatically registers the FileInfoMetadataSource and ExifToolMetadataSource instances, making them immediately available for use in metadata collection.
Definition at line 10 of file FIRECatalog.cs.
Referenced by FIRECatalog().
Register()
void DllImport::Register (IMetadataSource source)
Registers or replaces a metadata source in the registry.
Parameters
source The metadata source to register.
If a source with the same name (case-insensitive) is already registered, it is replaced. The source name is obtained from IMetadataSource.SourceName.
Variable Documentation
_exifTool
FileInfoMetadataSource _exifTool
Referenced by Dispose(), ExifToolMetadataSource(), and ExtractMetadata().
CreationTime
System Runtime InteropServices ComTypes FILETIME CreationTime
Definition at line 511 of file FIRECatalog.cs.
FileAlignmentInfo
FileAlignmentInfo = 17
Definition at line 17 of file FIRECatalog.cs.
FileAllocationInfo
FileAllocationInfo = 5
Definition at line 5 of file FIRECatalog.cs.
FileAttributes
struct FILE_ID_INFO FileAttributes
FileAttributeTagInfo
FileAttributeTagInfo = 9
Definition at line 9 of file FIRECatalog.cs.
FileBasicInfo
FileBasicInfo = 0
Definition at line 0 of file FIRECatalog.cs.
FileCompressionInfo
FileCompressionInfo = 8
Definition at line 8 of file FIRECatalog.cs.
FileDispositionInfo
FileDispositionInfo = 4
Definition at line 4 of file FIRECatalog.cs.
FileEndOfFileInfo
FileEndOfFileInfo = 6
Definition at line 6 of file FIRECatalog.cs.
FileFullDirectoryInfo
FileFullDirectoryInfo = 14
Definition at line 14 of file FIRECatalog.cs.
FileFullDirectoryRestartInfo
FileFullDirectoryRestartInfo = 15
Definition at line 15 of file FIRECatalog.cs.
FileIdBothDirectoryInfo
FileIdBothDirectoryInfo = 10
Definition at line 10 of file FIRECatalog.cs.
FileIdBothDirectoryRestartInfo
FileIdBothDirectoryRestartInfo = 11
Definition at line 11 of file FIRECatalog.cs.
FileIdExtdDirectoryInfo
FileIdExtdDirectoryInfo = 19
Definition at line 19 of file FIRECatalog.cs.
FileIdExtdDirectoryRestartInfo
FileIdExtdDirectoryRestartInfo = 20
Definition at line 20 of file FIRECatalog.cs.
FileIdInfo
FileIdInfo = 18
Definition at line 18 of file FIRECatalog.cs.
FileIndexHigh
uint FileIndexHigh
Definition at line 518 of file FIRECatalog.cs.
FileIndexLow
uint FileIndexLow
Definition at line 519 of file FIRECatalog.cs.
FileIoPriorityHintInfo
FileIoPriorityHintInfo = 12
Definition at line 12 of file FIRECatalog.cs.
FileNameInfo
FileNameInfo = 2
Definition at line 2 of file FIRECatalog.cs.
FileRemoteProtocolInfo
FileRemoteProtocolInfo = 13
Definition at line 13 of file FIRECatalog.cs.
FileRenameInfo
FileRenameInfo = 3
Definition at line 3 of file FIRECatalog.cs.
FileSizeHigh
uint FileSizeHigh
Definition at line 515 of file FIRECatalog.cs.
FileSizeLow
uint FileSizeLow
Definition at line 516 of file FIRECatalog.cs.
FileStandardInfo
FileStandardInfo = 1
Definition at line 1 of file FIRECatalog.cs.
FileStorageInfo
FileStorageInfo = 16
Definition at line 16 of file FIRECatalog.cs.
FileStreamInfo
FileStreamInfo = 7
Definition at line 7 of file FIRECatalog.cs.
IMetadataSource
FileInfoMetadataSource IMetadataSource
Metadata source for extracting embedded file metadata using ExifTool.
ExifToolMetadataSource integrates SharpExifTool to provide access to all embedded metadata in files (EXIF, IPTC, XMP, and other formats). It supports a wide range of file types and extracts comprehensive metadata that is typically used for photo/video sorting and management.
Extracted Metadata: This source can extract metadata such as:
Camera make, model, and lens
Capture date/time (DateTimeOriginal, DateTimeDigitized, etc.)
Image dimensions, orientation, color space
GPS coordinates and location data
XMP comments, keywords, ratings
Async/Await Integration: SharpExifTool uses async APIs, but this implementation synchronously blocks using GetAwaiter().GetResult() to fit the synchronous interface contract.
Error Handling: If the file does not exist, ExifTool is unavailable, or metadata extraction fails, the source returns an empty or partial metadata dictionary. Exceptions are caught to prevent disrupting the collection pipeline.
Resource Management: This class implements IDisposable to clean up the SharpExifTool instance. Always dispose of this source when done to release system resources.
Registration: This source is automatically registered when a MetadataSourceRegistry is created. It is referenced with the source name "EXIFTOOL" in configuration files.
Using ExifToolMetadataSource directly:
using (var exifSource = new ExifToolMetadataSource())
{
    var metadata = exifSource.ExtractMetadata("photo.jpg");
    foreach (var kvp in metadata)
    {
        Console.WriteLine($"{kvp.Key}: {kvp.Value}");
    }
}
Referenced by MetadataSourceRegistry::GetSource(), and MetadataSourceRegistry::Register().
LastAccessTime
System Runtime InteropServices ComTypes FILETIME LastAccessTime
Definition at line 512 of file FIRECatalog.cs.
LastWriteTime
System Runtime InteropServices ComTypes FILETIME LastWriteTime
Definition at line 513 of file FIRECatalog.cs.
lpFileInformation
sealed class MetadataSourceRegistry out BY_HANDLE_FILE_INFORMATION lpFileInformation
Definition at line 477 of file FIRECatalog.cs.
MaximumFileInfoByHandleClass
MaximumFileInfoByHandleClass
Definition at line 21 of file FIRECatalog.cs.
NumberOfLinks
uint NumberOfLinks
Definition at line 517 of file FIRECatalog.cs.
SourceName
string SourceName { get
Gets the name of the metadata source.
Gets the name of this metadata source.
This name is used to register and look up the source in MetadataSourceRegistry. Standard names include "FILEINFO" and "EXIFTOOL".
This always returns "EXIFTOOL".
Definition at line 109 of file FIRECatalog.cs.
string
enum FileInfoByHandleClass string
Defines an abstraction for metadata extraction from files.
IMetadataSource establishes a contract for extracting key-value metadata from files. Implementations provide different metadata origins, such as file system properties or embedded EXIF/IPTC/XMP data. Multiple sources can be registered in MetadataSourceRegistry and used during the collection phase.
Metadata Sources: Different implementations provide different metadata origins:
FileInfoMetadataSource: File system properties (CreationTime, ModificationTime, AccessTime)
ExifToolMetadataSource: Embedded file metadata via ExifTool (EXIF, IPTC, XMP)
Error Handling: Implementations should gracefully handle missing files or extraction failures by returning an empty or partial metadata dictionary. Exceptions should be caught to prevent disrupting the collection pipeline.
Extracts all available metadata key-value pairs from the specified file.
Parameters
filePath Absolute path to the file from which to extract metadata.
Returns
A dictionary of metadata key-value pairs. Keys are case-insensitive tag/property names, values are string representations of the metadata. Returns an empty dictionary if the file does not exist or extraction fails.
This method is called during the collection phase for each discovered file. Implementations should handle missing files and extraction errors gracefully.
VolumeSerialNumber
uint VolumeSerialNumber
Definition at line 514 of file FIRECatalog.cs.