/********************************************************************************
 * MIT License
 *
 * Copyright (c) 2025 Thoms Stoll
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 ********************************************************************************/

using Microsoft.EntityFrameworkCore;
using System.Collections;

namespace FIRE;

/// <summary>
/// Represents a single metadata entry stored together with a database record.
/// 
/// Each <c>FIREFileMetaData</c> instance encapsulates a key-value pair extracted
/// from a file, along with metadata about the value's type and source origin.
/// Multiple metadata entries are grouped into a single <see cref="FIREDbRecord"/>.
/// </summary>
/// <remarks>
/// This class is used as a domain model in the FIRE library. It is persisted
/// to the SQLite database via Entity Framework Core and mapped to/from the
/// internal <c>FIREFileMetaDataEntity</c> class.
/// 
/// Typical metadata keys include:
/// <list type="bullet">
/// <item><description>Make, Model (camera information from EXIF)</description></item>
/// <item><description>DateTimeOriginal, DateTimeDigitized (from EXIF)</description></item>
/// <item><description>CreationTime, ModificationTime (from file system)</description></item>
/// <item><description>Custom keyword names resolved from configuration</description></item>
/// </list>
/// 
/// The <see cref="DataSource"/> value typically indicates which
/// <see cref="IMetadataSource"/> provided the entry (e.g., "EXIFTOOL", "FILEINFO").
/// </remarks>
/// <example>
/// Creating and populating metadata entries:
/// <code>
/// var metadata = new FIREFileMetaData
/// {
///     Key = "Make",
///     Value = "Apple",
///     TypeName = typeof(string).FullName,
///     DataSource = "EXIFTOOL"
/// };
/// </code>
/// </example>
public class FIREFileMetaData
{
    /// <summary>
    /// Gets or sets the database identifier (primary key) of the metadata row.
    /// </summary>
    /// <remarks>
    /// This is auto-generated by the SQLite database when the row is inserted.
    /// Typically, you do not set this value manually; it is managed by Entity Framework Core.
    /// </remarks>
    public long Id { get; set; }

    /// <summary>
    /// Gets or sets the metadata key name.
    /// </summary>
    /// <remarks>
    /// Examples: "Make", "Model", "DateTimeOriginal", "CreationTime".
    /// This key corresponds to the keyword name defined in the FIRE configuration.
    /// </remarks>
    public string? Key { get; set; }

    /// <summary>
    /// Gets or sets the metadata value as a string.
    /// </summary>
    /// <remarks>
    /// All metadata values are stored as strings, regardless of their logical type.
    /// The logical type is recorded separately in the <see cref="TypeName"/> property.
    /// For example, an integer resolution value might be stored as "300" with
    /// TypeName set to "System.Int32".
    /// </remarks>
    public string? Value { get; set; }

    /// <summary>
    /// Gets or sets the CLR type name of the logical value.
    /// </summary>
    /// <remarks>
    /// This is the fully qualified name of the original .NET type,
    /// such as "System.String", "System.Int32", "System.DateTime".
    /// It is recorded to support type-aware parsing and formatting when
    /// the value is used in template placeholders.
    /// </remarks>
    public string? TypeName { get; set; }

    /// <summary>
    /// Gets or sets the source of the metadata value.
    /// </summary>
    /// <remarks>
    /// Valid values include "EXIFTOOL" (extracted via ExifTool) and "FILEINFO"
    /// (extracted from the file system). This field is useful for auditing and
    /// debugging the metadata collection process.
    /// </remarks>
    public string? DataSource { get; set; }
}

/// <summary>
/// Categorizes files by their role in the collection.
/// </summary>
/// <remarks>
/// This enum allows FIRE to distinguish between different file types during
/// processing. Regular files are processed normally through the metadata extraction
/// and path generation pipeline. Sidecar files inherit the target path from their
/// associated primary file (only the extension differs).
/// </remarks>
/// <remarks>
/// <para>
/// This enumeration distinguishes between primary files that are processed
/// through the normal metadata extraction pipeline and auxiliary sidecar files
/// that inherit path generation from their associated primary file.
/// </para>
/// <para>
/// During the collection phase, sidecar files are automatically detected based on
/// the <c>SidecarFileExtensions</c> configuration and added to the database with
/// <see cref="SidecarFile"/> classification. In the generate phase, they inherit
/// the target directory and base filename from their primary file. In the execute
/// phase, they use the global action setting.
/// </para>
/// </remarks>
public enum FileClassification
{
    /// <summary>
    /// A regular primary file processed through the full FIRE pipeline.
    /// This is the default classification for all collected files.
    /// </summary>
    /// <remarks>
    /// Regular files (e.g., .jpg, .mp4, .dng) undergo metadata extraction,
    /// template-based path generation, and file operations according to their
    /// extension-specific configuration.
    /// </remarks>
    RegularFile = 0,

    /// <summary>
    /// A sidecar file (e.g., .xmp, .pp3) that follows its primary file.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Sidecar files contain auxiliary metadata or processing instructions
    /// and are typically processed alongside their primary file.
    /// </para>
    /// <para>
    /// Sidecar files inherit the target path from their primary file during
    /// the generate phase and use the global action during the execute phase.
    /// They are detected automatically when listed in the primary file's
    /// <c>SidecarFileExtensions</c> configuration.
    /// </para>
    /// </remarks>
    SidecarFile = 1

    // Future extensions: ThumbnailFile, MetadataFile, PreviewFile, etc.
}

/// <summary>
/// Represents one complete file record persisted in the FIRE database.
/// 
/// Each <c>FIREDbRecord</c> corresponds to a single source file that has been
/// scanned and catalogued by the FIRE pipeline. It stores file identification
/// information, paths, and all metadata collected from the file.
/// </summary>
/// <remarks>
/// A <c>FIREDbRecord</c> is the primary domain model for FIRE. It typically
/// progresses through the three-step pipeline as follows:
/// 
/// <list type="number">
/// <item>
///   <description><strong>collect:</strong> <see cref="SourceFilePath"/> is set,
///   and <see cref="FileMetaDatas"/> are populated from configured metadata sources.</description>
/// </item>
/// <item>
///   <description><strong>generate:</strong> <see cref="TargetFilePath"/> is computed
///   by evaluating path templates with resolved metadata values.</description>
/// </item>
/// <item>
///   <description><strong>execute:</strong> The file operation (Copy, Move, or Link)
///   is performed from <see cref="SourceFilePath"/> to <see cref="TargetFilePath"/>.</description>
/// </item>
/// </list>
/// 
/// The <see cref="VolumeSerialNumber"/> and <see cref="FileId"/> are used on
/// Windows/NTFS systems to detect hard links and duplicates, avoiding unnecessary
/// processing of the same physical file.
/// </remarks>
/// <example>
/// Creating a record after file collection:
/// <code>
/// var record = new FIREDbRecord
/// {
///     SourceFilePath = @"D:\Photos\IMG_1234.jpg",
///     VolumeSerialNumber = volumeSerialNumber,
///     FileId = fileId,
///     FileMetaDatas = new List&lt;FIREFileMetaData&gt;
///     {
///         new() { Key = "Make", Value = "Apple", DataSource = "EXIFTOOL" },
///         new() { Key = "Model", Value = "iPhone 15 Pro", DataSource = "EXIFTOOL" }
///     }
/// };
/// </code>
/// </example>
public class FIREDbRecord
{
    /// <summary>
    /// Gets or sets the volume serial number of the NTFS volume where the source file resides.
    /// </summary>
    /// <remarks>
    /// This is obtained via Windows API calls and is used to detect files on the
    /// same physical volume. On non-Windows systems, this field may remain zero.
    /// Used by FIRE to identify and potentially skip duplicate files on the same volume.
    /// </remarks>
    public ulong VolumeSerialNumber { get; set; }

    /// <summary>
    /// Gets or sets the binary file identifier from the NTFS file system, if available.
    /// </summary>
    /// <remarks>
    /// This 16-byte identifier is unique per file on the NTFS volume and persists
    /// even if the file is renamed or moved. It is obtained via the Windows API's
    /// <c>GetFileInformationByHandleEx</c> function. This field is null on non-NTFS systems
    /// or if the API call fails.
    /// 
    /// File IDs are useful for detecting hard links to the same physical file,
    /// which is important for avoiding duplicate processing.
    /// </remarks>
    public byte[]? FileId { get; set; }

    /// <summary>
    /// Gets or sets the original source file path as discovered during the <c>collect</c> phase.
    /// </summary>
    /// <remarks>
    /// This is the absolute path to the source file before any file operation is performed.
    /// It is populated during the <c>collect</c> phase and should not be modified thereafter.
    /// 
    /// Example: <c>D:\Photos\Import\IMG_1234.jpg</c>
    /// </remarks>
    public string? SourceFilePath { get; set; }

    /// <summary>
    /// Gets or sets the computed target file path, as determined during the <c>generate</c> phase.
    /// </summary>
    /// <remarks>
    /// This path is calculated by evaluating the <c>SortingPatern</c> and <c>FileNamePatern</c>
    /// configuration templates with resolved metadata values. It is set to null initially
    /// and is populated during the <c>generate</c> phase. It is then used during the
    /// <c>execute</c> phase to perform the actual file operation (Copy, Move, or Link).
    /// 
    /// Example: <c>D:\Photos\Sorted\2026\07\Apple iPhone 15 Pro\2026-07-04_IMG_1234.jpg</c>
    /// </remarks>
    public string? TargetFilePath { get; set; }

    /// <summary>
    /// Gets or sets the classification of this file.
    /// </summary>
    /// <remarks>
    /// Determines how the file is processed during the generate phase.
    /// Regular files have their target paths computed from templates,
    /// while sidecar files inherit the target path from their associated primary file.
    /// Defaults to <see cref="FileClassification.RegularFile"/>.
    /// </remarks>
    public FileClassification Classification { get; set; } = FileClassification.RegularFile;

    /// <summary>
    /// Gets or sets the file metadata entries associated with this record.
    /// </summary>
    /// <remarks>
    /// This collection is populated during the <c>collect</c> phase by querying
    /// all configured metadata sources (EXIFTOOL, FILEINFO, etc.) for the file.
    /// The collection is persisted to the database as child rows in a one-to-many
    /// relationship. Each entry in this list corresponds to a single keyword resolved
    /// from the FIRE configuration.
    /// </remarks>
    public List<FIREFileMetaData> FileMetaDatas { get; set; } = [];
}

/// <summary>
/// Represents the current status and state of the database content and recent persistence operations.
/// </summary>
/// <remarks>
/// There is exactly one <c>FIREStatusRecord</c> row in the database at all times
/// (with <see cref="Id"/> equal to 1). It is created during <see cref="FIREDatabase"/>
/// initialization and is updated after every persistence operation (Save, Add, Clear, etc.).
/// 
/// The status indicates the result of the most recent operation:
/// <list type="bullet">
/// <item><description><c>Initialized</c> – Database was just created</description></item>
/// <item><description><c>Saved</c> – Last operation completed successfully</description></item>
/// <item><description><c>Failed</c> – The last operation encountered an error</description></item>
/// <item><description><c>Saving</c> – Operation in progress (rarely observed)</description></item>
/// </list>
/// 
/// The <see cref="Valid"/> field indicates whether the stored data set is consistent
/// and complete. It is set to false when an error occurs during persistence.
/// The <see cref="ErrorMessage"/> field captures the exception message if <see cref="Valid"/> is false.
/// </remarks>
/// <example>
/// Checking the database status after a batch operation:
/// <code>
/// var status = database.StatusRecord;
/// if (!status.Valid)
/// {
///     Console.WriteLine($"Error: {status.ErrorMessage}");
/// }
/// else
/// {
///     Console.WriteLine($"Last operation: {status.Status} at {status.TimeStamp:O}");
/// }
/// </code>
/// </example>
public class FIREStatusRecord
{
    /// <summary>
    /// Gets or sets the database identifier (primary key) of the status row.
    /// </summary>
    /// <remarks>
    /// This is always 1 (see <c>FIREDatabaseStatusEntity.SingletonId</c>) to enforce
    /// the singleton pattern. Only one status row exists in the database.
    /// </remarks>
    public long Id { get; set; }

    /// <summary>
    /// Gets or sets a textual status value describing the result of the most recent operation.
    /// </summary>
    /// <remarks>
    /// Typical values: "Ready", "Saving", "Saved", "Completed", "Failed", "Initialized", "Cleared".
    /// This status is updated immediately before and after each persistence operation.
    /// </remarks>
    public string? Status { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether the stored data set is valid and complete.
    /// </summary>
    /// <remarks>
    /// This is true if the most recent operation succeeded. If an exception occurs
    /// during persistence, this is set to false and <see cref="ErrorMessage"/> is populated.
    /// Can be used as a quick health check for the database state.
    /// </remarks>
    public bool Valid { get; set; }

    /// <summary>
    /// Gets or sets the UTC timestamp when the status was last changed.
    /// </summary>
    /// <remarks>
    /// This timestamp is updated after every persistence operation and is useful
    /// for auditing and monitoring the database activity timeline.
    /// </remarks>
    public DateTime? TimeStamp { get; set; }

    /// <summary>
    /// Gets or sets an optional error message for failed operations.
    /// </summary>
    /// <remarks>
    /// This field is populated only if <see cref="Valid"/> is false.
    /// It contains the <c>Message</c> of the exception that was caught
    /// during the most recent persistence operation.
    /// </remarks>
    public string? ErrorMessage { get; set; }
}

/// <summary>
/// Provides a list-like interface to <see cref="FIREDbRecord"/> file entries backed by a SQLite database.
/// 
/// <c>FIREDatabase</c> combines Entity Framework Core with SQLite persistence to provide
/// a simple in-memory collection abstraction over stored file records. It implements
/// the <see cref="IList{T}"/> interface, allowing standard collection operations
/// while automatically persisting changes to the database.
/// </summary>
/// <remarks>
/// <para>
/// <strong>Architecture:</strong>
/// The class maintains an in-memory <c>_records</c> list and a <see cref="FIREDatabaseContext"/>
/// for EF Core operations. When you modify the collection (Add, Remove, Clear, etc.),
/// the changes are immediately persisted to the underlying SQLite database via
/// <c>PersistCurrentState</c>, which wraps the entire operation in a transaction.
/// </para>
/// 
/// <para>
/// <strong>Initialization:</strong>
/// When you create a new instance, the SQLite file is created if it doesn't exist.
/// If <c>recreateIfExists</c> is true, any existing database is deleted first.
/// A singleton status row is automatically initialized to track database state.
/// </para>
/// 
/// <para>
/// <strong>Reload and Persistence:</strong>
/// The <see cref="Reload"/> method reloads all records from the database into memory.
/// The <see cref="Save"/> method persists the current in-memory list to the database.
/// Every modification operation (Add, Remove, etc.) automatically calls <c>PersistCurrentState</c>
/// to flush changes to the database immediately.
/// </para>
/// 
/// <para>
/// <strong>Status Tracking:</strong>
/// The <see cref="StatusRecord"/> property provides access to the singleton status row,
/// which records the result and timestamp of the most recent operation.
/// If a persistence operation fails, the status is set to "Failed" and the error message is recorded.
/// </para>
/// 
/// <para>
/// <strong>Thread Safety:</strong>
/// This class is not inherently thread-safe. Multiple concurrent modifications to the
/// same database from different threads or processes will likely result in conflicts.
/// Ensure external synchronization if concurrent access is required.
/// </para>
/// </remarks>
/// <example>
/// Creating a database and adding records:
/// <code>
/// using var db = new FIREDatabase("D:\\data\\fire.db", recreateIfExists: true);
/// 
/// var record = new FIREDbRecord
/// {
///     SourceFilePath = @"D:\Photos\IMG_1234.jpg",
///     FileMetaDatas = new List&lt;FIREFileMetaData&gt;
///     {
///         new() { Key = "Make", Value = "Nikon" }
///     }
/// };
/// 
/// db.Add(record);
/// Console.WriteLine($"Total records: {db.Count}");
/// Console.WriteLine($"Status: {db.StatusRecord.Status}");
/// </code>
/// </example>
public sealed class FIREDatabase : IList<FIREDbRecord>, IDisposable
{
    private readonly string _databaseFilePath;
    private readonly List<FIREDbRecord> _records = [];
    private readonly FIREDatabaseContext _context;
    private bool _disposed;

    private readonly FIREStatusRecord _statusRecord = new();

    /// <summary>
    /// Creates a new instance of <c>FIREDatabase</c> backed by the specified SQLite file.
    /// </summary>
    /// <param name="databaseFilePath">
    /// Full path to the SQLite database file. If the directory does not exist, it is created.
    /// If <paramref name="recreateIfExists"/> is true and the file exists, it will be deleted.
    /// </param>
    /// <param name="recreateIfExists">
    /// If true, any existing database file is deleted and recreated from scratch.
    /// If false (the default), an existing database is reused.
    /// </param>
    /// <exception cref="ArgumentException">
    /// Thrown if <paramref name="databaseFilePath"/> is null, empty, or whitespace.
    /// </exception>
    /// <exception cref="IOException">
    /// Thrown if the directory cannot be created or the database file cannot be accessed.
    /// </exception>
    public FIREDatabase(string databaseFilePath, bool recreateIfExists = false)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(databaseFilePath);

        _databaseFilePath = Path.GetFullPath(databaseFilePath);
        var directory = Path.GetDirectoryName(_databaseFilePath);
        if (!string.IsNullOrWhiteSpace(directory))
        {
            Directory.CreateDirectory(directory);
        }

        var options = new DbContextOptionsBuilder<FIREDatabaseContext>()
            .UseSqlite($"Data Source={_databaseFilePath}")
            .Options;

        _context = new FIREDatabaseContext(options);

        if (recreateIfExists && File.Exists(_databaseFilePath))
        {
            _context.Database.EnsureDeleted();
        }

        _context.Database.EnsureCreated();
        EnsureStatusRowExists();
        Reload();
    }

    /// <summary>
    /// Gets the file path of the backing SQLite database.
    /// </summary>
    public string DatabaseFilePath => _databaseFilePath;

    /// <summary>
    /// Gets the current persisted database status record.
    /// </summary>
    /// <remarks>
    /// This property returns a reference to the singleton status row that is
    /// updated after every persistence operation. Inspect this record to check
    /// the result of the last operation and any error messages.
    /// </remarks>
    public FIREStatusRecord StatusRecord => _statusRecord;

    /// <summary>
    /// Reloads all file records from the SQLite database into the in-memory collection.
    /// </summary>
    /// <remarks>
    /// This method clears the current in-memory list and repopulates it from the database.
    /// It also reloads the singleton status record. Use this method to sync in-memory state
    /// with the database after an external modification (e.g., another process updating the file).
    /// </remarks>
    /// <exception cref="ObjectDisposedException">
    /// Thrown if this instance has been disposed.
    /// </exception>
    public void Reload()
    {
        ThrowIfDisposed();

        _records.Clear();
        _records.AddRange(_context.FileRecords
            .AsNoTracking()
            .Include(record => record.FileMetaDatas)
            .OrderBy(record => record.Id)
            .Select(MapToModel));

        var statusEntity = _context.StatusRecords.AsNoTracking().SingleOrDefault(x => x.Id == FIREDatabaseStatusEntity.SingletonId);
        if (statusEntity is not null)
        {
            CopyToModel(statusEntity, _statusRecord);
        }
    }

    /// <summary>
    /// Recreates the SQLite database file from scratch.
    /// </summary>
    /// <remarks>
    /// This method deletes the entire database, recreates it with all schema tables,
    /// and initializes the singleton status row. All in-memory records are cleared,
    /// and the status is updated to "Recreated".
    /// </remarks>
    /// <exception cref="ObjectDisposedException">
    /// Thrown if this instance has been disposed.
    /// </exception>
    public void RecreateDatabase()
    {
        ThrowIfDisposed();

        _context.Database.EnsureDeleted();
        _context.Database.EnsureCreated();
        EnsureStatusRowExists();
        _records.Clear();
        PersistCurrentState("Recreated", true, null);
        Reload();
    }

    /// <summary>
    /// Persists the current in-memory collection to the SQLite database.
    /// </summary>
    /// <remarks>
    /// This method replaces all records in the database with the current in-memory
    /// collection and updates the status to "Saved". The operation is wrapped in
    /// a database transaction for atomicity.
    /// </remarks>
    /// <exception cref="ObjectDisposedException">
    /// Thrown if this instance has been disposed.
    /// </exception>
    /// <exception cref="Exception">
    /// If the persistence operation fails, the status record is updated to "Failed"
    /// with the error message, and the exception is rethrown.
    /// </exception>
    public void Save()
    {
        ThrowIfDisposed();
        PersistCurrentState("Saved", true, null);
        Reload();
    }

    /// <summary>
    /// Adds a new record to the collection and persists the change immediately.
    /// </summary>
    /// <param name="item">The <see cref="FIREDbRecord"/> to add.</param>
    /// <remarks>
    /// The record is added to the in-memory list and immediately persisted to the database
    /// via a <c>PersistCurrentState</c> call. After persistence, the entire collection is
    /// reloaded from the database to ensure consistency.
    /// </remarks>
    /// <exception cref="ArgumentNullException">
    /// Thrown if <paramref name="item"/> is null.
    /// </exception>
    /// <exception cref="ObjectDisposedException">
    /// Thrown if this instance has been disposed.
    /// </exception>
    public void Add(FIREDbRecord item)
    {
        ArgumentNullException.ThrowIfNull(item);
        ThrowIfDisposed();

        _records.Add(item);
        PersistCurrentState("Added", true, null);
        Reload();
    }

    /// <summary>
    /// Removes all records from the collection and persists the change immediately.
    /// </summary>
    /// <remarks>
    /// This method clears the in-memory list, persists the empty state to the database,
    /// and reloads. After this call, the database contains no file records.
    /// </remarks>
    /// <exception cref="ObjectDisposedException">
    /// Thrown if this instance has been disposed.
    /// </exception>
    public void Clear()
    {
        ThrowIfDisposed();

        _records.Clear();
        PersistCurrentState("Cleared", true, null);
        Reload();
    }

    /// <summary>
    /// Determines whether the specified record is present in the current collection.
    /// </summary>
    /// <param name="item">The record to locate.</param>
    /// <returns>true if the record is in the collection; otherwise, false.</returns>
    public bool Contains(FIREDbRecord item) => _records.Contains(item);

    /// <summary>
    /// Copies the in-memory collection to the specified array, starting at the specified index.
    /// </summary>
    /// <param name="array">The destination array.</param>
    /// <param name="arrayIndex">The zero-based index in the array where copying begins.</param>
    public void CopyTo(FIREDbRecord[] array, int arrayIndex) => _records.CopyTo(array, arrayIndex);

    /// <summary>
    /// Returns the number of records currently loaded in memory.
    /// </summary>
    public int Count => _records.Count;

    /// <summary>
    /// Gets a value indicating whether the collection is read-only.
    /// </summary>
    /// <remarks>
    /// This property always returns false because changes to the collection are allowed
    /// and are persisted to the database.
    /// </remarks>
    public bool IsReadOnly => false;

    /// <summary>
    /// Gets or sets the record at the specified index.
    /// </summary>
    /// <param name="index">The zero-based index of the record to get or set.</param>
    /// <returns>The record at the specified index.</returns>
    /// <remarks>
    /// Setting a value at an index persists the change immediately to the database
    /// via a <c>PersistCurrentState</c> call and then reloads the collection.
    /// </remarks>
    /// <exception cref="ArgumentNullException">
    /// Thrown when attempting to set a null value at an index.
    /// </exception>
    /// <exception cref="ObjectDisposedException">
    /// Thrown if this instance has been disposed.
    /// </exception>
    public FIREDbRecord this[int index]
    {
        get => _records[index];
        set
        {
            ThrowIfDisposed();
            _records[index] = value ?? throw new ArgumentNullException(nameof(value));
            PersistCurrentState("Updated", true, null);
            Reload();
        }
    }

    /// <summary>
    /// Returns the zero-based index of the specified record in the collection.
    /// </summary>
    /// <param name="item">The record to locate.</param>
    /// <returns>The index of the record, or -1 if it is not found.</returns>
    public int IndexOf(FIREDbRecord item) => _records.IndexOf(item);

    /// <summary>
    /// Inserts a record at the specified index and persists the change.
    /// </summary>
    /// <param name="index">The zero-based index at which the record should be inserted.</param>
    /// <param name="item">The record to insert.</param>
    /// <remarks>
    /// The record is inserted into the in-memory list at the specified position, then
    /// persisted to the database immediately via <c>PersistCurrentState</c> and reloaded.
    /// </remarks>
    /// <exception cref="ArgumentNullException">
    /// Thrown if <paramref name="item"/> is null.
    /// </exception>
    /// <exception cref="ObjectDisposedException">
    /// Thrown if this instance has been disposed.
    /// </exception>
    public void Insert(int index, FIREDbRecord item)
    {
        ArgumentNullException.ThrowIfNull(item);
        ThrowIfDisposed();

        _records.Insert(index, item);
        PersistCurrentState("Inserted", true, null);
        Reload();
    }

    /// <summary>
    /// Removes the specified record from the collection by value.
    /// </summary>
    /// <param name="item">The record to remove.</param>
    /// <returns>true if the record was found and removed; otherwise, false.</returns>
    /// <remarks>
    /// If the record is found, it is removed from the in-memory list and the change is
    /// persisted to the database immediately. If the record is not found, no change
    /// is made and false is returned.
    /// </remarks>
    /// <exception cref="ObjectDisposedException">
    /// Thrown if this instance has been disposed.
    /// </exception>
    public bool Remove(FIREDbRecord item)
    {
        ThrowIfDisposed();

        var removed = _records.Remove(item);
        if (removed)
        {
            PersistCurrentState("Removed", true, null);
            Reload();
        }

        return removed;
    }

    /// <summary>
    /// Removes the record at the specified index and persists the change.
    /// </summary>
    /// <param name="index">The zero-based index of the record to remove.</param>
    /// <remarks>
    /// The record at the specified index is removed from the in-memory list and
    /// the change is persisted to the database immediately.
    /// </remarks>
    /// <exception cref="ObjectDisposedException">
    /// Thrown if this instance has been disposed.
    /// </exception>
    public void RemoveAt(int index)
    {
        ThrowIfDisposed();

        _records.RemoveAt(index);
        PersistCurrentState("Removed", true, null);
        Reload();
    }

    /// <summary>
    /// Disposes the underlying Entity Framework Core database context.
    /// </summary>
    /// <remarks>
    /// After calling this method, all operations on this instance will throw
    /// <see cref="ObjectDisposedException"/>. This method is safe to call multiple times.
    /// </remarks>
    public void Dispose()
    {
        if (_disposed)
        {
            return;
        }

        _context.Dispose();
        _disposed = true;
    }

    /// <summary>
    /// Gets a read-only snapshot view of the current in-memory records.
    /// </summary>
    /// <returns>A <see cref="IReadOnlyList{T}"/> containing the current records.</returns>
    /// <remarks>
    /// The returned collection is a snapshot at the time of the call and does not reflect
    /// subsequent modifications to the database.
    /// </remarks>
    public IReadOnlyList<FIREDbRecord> AsReadOnlyList() => _records.AsReadOnly();

    /// <summary>
    /// Returns an enumerator that iterates through the records in the collection.
    /// </summary>
    public IEnumerator<FIREDbRecord> GetEnumerator() => _records.GetEnumerator();

    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();

    private void EnsureStatusRowExists()
    {
        if (_context.StatusRecords.Any(x => x.Id == FIREDatabaseStatusEntity.SingletonId))
        {
            return;
        }

        _context.StatusRecords.Add(new FIREStatusEntity
        {
            Id = FIREDatabaseStatusEntity.SingletonId,
            Status = "Initialized",
            Valid = true,
            TimeStamp = DateTime.UtcNow,
            ErrorMessage = null
        });

        _context.SaveChanges();
        CopyToModel(_context.StatusRecords.Single(x => x.Id == FIREDatabaseStatusEntity.SingletonId), _statusRecord);
    }

    private void PersistCurrentState(string status, bool valid, string? errorMessage)
    {
        try
        {
            using var transaction = _context.Database.BeginTransaction();

            var existingRecords = _context.FileRecords.Include(record => record.FileMetaDatas).ToList();
            if (existingRecords.Count > 0)
            {
                _context.FileMetaDataRecords.RemoveRange(existingRecords.SelectMany(record => record.FileMetaDatas));
                _context.FileRecords.RemoveRange(existingRecords);
                _context.SaveChanges();
            }

            foreach (var record in _records)
            {
                _context.FileRecords.Add(MapToEntity(record));
            }

            var statusEntity = _context.StatusRecords.Single(x => x.Id == FIREDatabaseStatusEntity.SingletonId);
            statusEntity.Status = status;
            statusEntity.Valid = valid;
            statusEntity.ErrorMessage = errorMessage;
            statusEntity.TimeStamp = DateTime.UtcNow;

            _context.SaveChanges();
            transaction.Commit();
            CopyToModel(statusEntity, _statusRecord);
        }
        catch (Exception ex)
        {
            try
            {
                var statusEntity = _context.StatusRecords.Single(x => x.Id == FIREDatabaseStatusEntity.SingletonId);
                statusEntity.Status = "Failed";
                statusEntity.Valid = false;
                statusEntity.ErrorMessage = ex.Message;
                statusEntity.TimeStamp = DateTime.UtcNow;
                _context.SaveChanges();
                CopyToModel(statusEntity, _statusRecord);
            }
            catch
            {
                // If the status cannot be updated, the original exception is preserved.
            }

            throw;
        }
    }

    private static FIREDbRecord MapToModel(FIREDbRecordEntity entity)
    {
        var model = new FIREDbRecord
        {
            VolumeSerialNumber = entity.VolumeSerialNumber,
            FileId = entity.FileId,
            SourceFilePath = entity.SourceFilePath,
            TargetFilePath = entity.TargetFilePath,
            Classification = entity.Classification,
            FileMetaDatas = entity.FileMetaDatas
                .OrderBy(meta => meta.Id)
                .Select(meta => new FIREFileMetaData
                {
                    Id = meta.Id,
                    Key = meta.Key,
                    Value = meta.Value,
                    TypeName = meta.TypeName,
                    DataSource = meta.DataSource
                })
                .ToList()
        };

        return model;
    }

    private static FIREDbRecordEntity MapToEntity(FIREDbRecord model)
    {
        var entity = new FIREDbRecordEntity
        {
            VolumeSerialNumber = model.VolumeSerialNumber,
            FileId = model.FileId,
            SourceFilePath = model.SourceFilePath,
            TargetFilePath = model.TargetFilePath,
            Classification = model.Classification
        };

        foreach (var meta in model.FileMetaDatas)
        {
            entity.FileMetaDatas.Add(new FIREFileMetaDataEntity
            {
                Id = meta.Id,
                Key = meta.Key,
                Value = meta.Value,
                TypeName = meta.TypeName,
                DataSource = meta.DataSource
            });
        }

        return entity;
    }

    private static void CopyToModel(FIREStatusEntity entity, FIREStatusRecord model)
    {
        model.Id = entity.Id;
        model.Status = entity.Status;
        model.Valid = entity.Valid;
        model.TimeStamp = entity.TimeStamp;
        model.ErrorMessage = entity.ErrorMessage;
    }

    private void ThrowIfDisposed()
    {
        if (_disposed)
        {
            throw new ObjectDisposedException(nameof(FIREDatabase));
        }
    }
}

/// <summary>
/// Entity Framework Core context for the FIRE SQLite database.
/// </summary>
/// <remarks>
/// This sealed internal class manages all database connections, migrations, and table mappings
/// for the FIRE SQLite database. It is used internally by <see cref="FIREDatabase"/> to
/// persist and retrieve file records, metadata entries, and status information.
/// 
/// The context configures three main tables:
/// <list type="bullet">
/// <item><description><c>FIREDbRecords</c> – File records with source and target paths.</description></item>
/// <item><description><c>FIREFileMetaDatas</c> – Metadata key-value pairs associated with each record.</description></item>
/// <item><description><c>FIREStatusRecord</c> – Singleton status row tracking database state.</description></item>
/// </list>
/// </remarks>
internal sealed class FIREDatabaseContext : DbContext
{
    /// <summary>
    /// Initializes a new instance of the <see cref="FIREDatabaseContext"/> class.
    /// </summary>
    /// <param name="options">Entity Framework Core context options.</param>
    public FIREDatabaseContext(DbContextOptions<FIREDatabaseContext> options)
        : base(options)
    {
    }

    /// <summary>
    /// Gets the DbSet for file records.
    /// </summary>
    public DbSet<FIREDbRecordEntity> FileRecords => Set<FIREDbRecordEntity>();

    /// <summary>
    /// Gets the DbSet for file metadata entries.
    /// </summary>
    public DbSet<FIREFileMetaDataEntity> FileMetaDataRecords => Set<FIREFileMetaDataEntity>();

    /// <summary>
    /// Gets the DbSet for the database status record.
    /// </summary>
    public DbSet<FIREStatusEntity> StatusRecords => Set<FIREStatusEntity>();

    /// <summary>
    /// Configures the data model and table mappings.
    /// </summary>
    /// <param name="modelBuilder">Builder used to configure the EF Core model.</param>
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<FIREDbRecordEntity>(entity =>
        {
            entity.ToTable("FIREDbRecords");
            entity.HasKey(x => x.Id);
            entity.Property(x => x.VolumeSerialNumber)
                .HasConversion(
                    value => checked((long)value),
                    value => checked((ulong)value));

            entity.Property(x => x.Classification)
                .HasConversion<int>()
                .HasDefaultValue(FileClassification.RegularFile);

            entity.HasMany(x => x.FileMetaDatas)
                .WithOne(x => x.Record)
                .HasForeignKey(x => x.RecordId)
                .OnDelete(DeleteBehavior.Cascade);
        });

        modelBuilder.Entity<FIREFileMetaDataEntity>(entity =>
        {
            entity.ToTable("FIREFileMetaDatas");
            entity.HasKey(x => x.Id);
        });

        modelBuilder.Entity<FIREStatusEntity>(entity =>
        {
            entity.ToTable("FIREStatusRecord");
            entity.HasKey(x => x.Id);
        });
    }
}

/// <summary>
/// Entity Framework Core entity class mapping to the FIREDbRecords table.
/// </summary>
/// <remarks>
/// This is an internal EF Core entity-mapped class used only within the data
/// persistence layer. It is not exposed in the public API; instead, the domain
/// model <see cref="FIREDbRecord"/> is used. This class includes navigation
/// properties for Entity Framework's lazy-loading and change-tracking capabilities.
/// </remarks>
internal sealed class FIREDbRecordEntity
{
    /// <summary>
    /// Gets or sets the auto-generated database identifier (primary key).
    /// </summary>
    public long Id { get; set; }

    /// <summary>
    /// Gets or sets the volume serial number from the NTFS file system.
    /// </summary>
    /// <remarks>
    /// This is stored as a long (int64) in the database and converted to/from
    /// the ulong (uint64) property via EF Core's value converters.
    /// </remarks>
    public ulong VolumeSerialNumber { get; set; }

    /// <summary>
    /// Gets or sets the binary file identifier from the NTFS file system.
    /// </summary>
    public byte[]? FileId { get; set; }

    /// <summary>
    /// Gets or sets the original source file path.
    /// </summary>
    public string? SourceFilePath { get; set; }

    /// <summary>
    /// Gets or sets the computed target file path.
    /// </summary>
    public string? TargetFilePath { get; set; }

    /// <summary>
    /// Gets or sets the classification of this file.
    /// </summary>
    /// <remarks>
    /// Stored as an integer in the database. Defaults to 0 (<see cref="FileClassification.RegularFile"/>).
    /// </remarks>
    public FileClassification Classification { get; set; } = FileClassification.RegularFile;

    /// <summary>
    /// Gets or sets the collection of file metadata entries associated with this record.
    /// </summary>
    /// <remarks>
    /// This is a navigation property used by EF Core for lazy-loading and cascade deletes.
    /// When a record is deleted, all associated metadata entries are also deleted due to
    /// the Cascade delete behavior configured in <see cref="FIREDatabaseContext.OnModelCreating(ModelBuilder)"/>.
    /// </remarks>
    public List<FIREFileMetaDataEntity> FileMetaDatas { get; set; } = [];
}

/// <summary>
/// Entity Framework Core entity class mapping to the FIREFileMetaDatas table.
/// </summary>
/// <remarks>
/// This is an internal EF Core entity-mapped class used only within the data
/// persistence layer. It corresponds to the domain model <see cref="FIREFileMetaData"/>.
/// The <see cref="Record"/> navigation property represents the one-to-many relationship
/// with <see cref="FIREDbRecordEntity"/>.
/// </remarks>
internal sealed class FIREFileMetaDataEntity
{
    /// <summary>
    /// Gets or sets the auto-generated database identifier (primary key).
    /// </summary>
    public long Id { get; set; }

    /// <summary>
    /// Gets or sets the foreign key to the parent file record.
    /// </summary>
    /// <remarks>
    /// This property links this metadata entry to its parent file record.
    /// It is required for maintaining the one-to-many relationship.
    /// </remarks>
    public long RecordId { get; set; }

    /// <summary>
    /// Gets or sets the parent file record (navigation property).
    /// </summary>
    /// <remarks>
    /// This navigation property is used by EF Core to establish the relationship
    /// between metadata entries and their parent record. In normal operation,
    /// you should not need to access this property directly; instead, work with
    /// the <see cref="FIREDbRecord.FileMetaDatas"/> collection from the record side.
    /// </remarks>
    public FIREDbRecordEntity? Record { get; set; }

    /// <summary>
    /// Gets or sets the metadata key.
    /// </summary>
    public string? Key { get; set; }

    /// <summary>
    /// Gets or sets the metadata value as a string.
    /// </summary>
    public string? Value { get; set; }

    /// <summary>
    /// Gets or sets the CLR type name of the logical value.
    /// </summary>
    public string? TypeName { get; set; }

    /// <summary>
    /// Gets or sets the source of the metadata value.
    /// </summary>
    public string? DataSource { get; set; }
}

/// <summary>
/// Entity Framework Core entity class mapping to the FIREStatusRecord table.
/// </summary>
/// <remarks>
/// This is an internal EF Core entity-mapped class used only within the data
/// persistence layer. It corresponds to the domain model <see cref="FIREStatusRecord"/>.
/// There is exactly one row in this table (with <see cref="Id"/> = 1) that tracks
/// the status of the most recent database operation.
/// </remarks>
internal sealed class FIREStatusEntity
{
    /// <summary>
    /// Gets or sets the database identifier (primary key).
    /// </summary>
    /// <remarks>
    /// This is always 1 (see <see cref="FIREDatabaseStatusEntity.SingletonId"/>) to enforce
    /// the singleton pattern.
    /// </remarks>
    public long Id { get; set; }

    /// <summary>
    /// Gets or sets the status of the most recent operation.
    /// </summary>
    public string? Status { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether the stored data set is valid.
    /// </summary>
    public bool Valid { get; set; }

    /// <summary>
    /// Gets or sets the UTC timestamp of the most recent status change.
    /// </summary>
    public DateTime? TimeStamp { get; set; }

    /// <summary>
    /// Gets or sets the error message, if the last operation failed.
    /// </summary>
    public string? ErrorMessage { get; set; }
}

/// <summary>
/// Provides constant values and utility constants for the FIRE database status infrastructure.
/// </summary>
/// <remarks>
/// This static class contains configuration constants for the database status singleton.
/// Currently, it defines the constant primary key ID for the status row, ensuring that
/// exactly one status record exists in the database at all times.
/// </remarks>
internal static class FIREDatabaseStatusEntity
{
    /// <summary>
    /// The singleton primary key value for the status record (always 1).
    /// </summary>
    /// <remarks>
    /// There is exactly one status record in the database, and its ID is always 1.
    /// This constant is used throughout the persistence layer to query, update, and
    /// retrieve the status record.
    /// </remarks>
    public const long SingletonId = 1;
}