FIRE: ConsoleUi Class Reference
ConsoleUi Class Reference
Static Public Member Functions
static void WriteTitle (RuntimeContext runtime, string text)
static void WriteLine (RuntimeContext runtime, string text)
static void WriteInfo (RuntimeContext runtime, string text)
static void WriteSuccess (RuntimeContext runtime, string text)
static void WriteWarning (RuntimeContext runtime, string text)
static void WriteWarning (UiLanguage language, bool noWrap, string text)
static void WriteError (RuntimeContext runtime, string text)
static void WriteError (UiLanguage language, bool noWrap, string text)
static void WriteProgress (RuntimeContext runtime, string text)
static void EndProgressLine ()
static void WriteEmptyLine ()
Detailed Description
Definition at line 547 of file Program.cs.
Member Function Documentation
EndProgressLine()
void ConsoleUi::EndProgressLine () inline static
Definition at line 614 of file Program.cs.
WriteEmptyLine()
void ConsoleUi::WriteEmptyLine () inline static
Definition at line 619 of file Program.cs.
Referenced by CommandExecutor::ExecuteCollect(), and CommandExecutor::ExecuteInspect().
WriteError() [1/2]
void ConsoleUi::WriteError (RuntimeContext runtime, string text) inline static
Definition at line 591 of file Program.cs.
References RuntimeContext().
Referenced by CommandExecutor::ExecuteInspect(), and ProgramHost::Run().
WriteError() [2/2]
void ConsoleUi::WriteError (UiLanguage language, bool noWrap, string text) inline static
Definition at line 599 of file Program.cs.
WriteInfo()
void ConsoleUi::WriteInfo (RuntimeContext runtime, string text) inline static
Definition at line 559 of file Program.cs.
References RuntimeContext().
Referenced by CommandExecutor::ExecuteInspect().
WriteLine()
void ConsoleUi::WriteLine (RuntimeContext runtime, string text) inline static
Definition at line 554 of file Program.cs.
References RuntimeContext().
Referenced by CommandExecutor::ExecuteCollect(), CommandExecutor::ExecuteInspect(), and WriteTitle().
WriteProgress()
void ConsoleUi::WriteProgress (RuntimeContext runtime, string text) inline static
Definition at line 607 of file Program.cs.
References RuntimeContext().
WriteSuccess()
void ConsoleUi::WriteSuccess (RuntimeContext runtime, string text) inline static
Definition at line 567 of file Program.cs.
References RuntimeContext().
Referenced by CommandExecutor::ExecuteInspect().
WriteTitle()
void ConsoleUi::WriteTitle (RuntimeContext runtime, string text) inline static
Definition at line 549 of file Program.cs.
References RuntimeContext(), and WriteLine().
Referenced by CommandExecutor::ExecuteInspect().
WriteWarning() [1/2]
void ConsoleUi::WriteWarning (RuntimeContext runtime, string text) inline static
Definition at line 575 of file Program.cs.
References RuntimeContext().
Referenced by CommandExecutor::ExecuteInspect(), and ProgramHost::Run().
WriteWarning() [2/2]
void ConsoleUi::WriteWarning (UiLanguage language, bool noWrap, string text) inline static
Definition at line 583 of file Program.cs.
The documentation for this class was generated from the following file:
FIRE/FIRE.Console/Program.cs