FIRE: FIRE/FIRE.Console/Program.cs File Reference
Program.cs File Reference
Classes
class ProgramHost
class GenerateCommand
class InspectCommand
class CommonCommandSettings
class InspectSettings
class CommandExecutor
class ConsoleUi
class AppLifetime
Enumerations
enum UiLanguage { English , German , French , Filipino }
Functions
return ProgramHost Run (args)
static internal class ProgramHost Execute (CommandContext context, CollectSettings settings)
static int Run (string[] args)
GenerateCommand Command Execute (CommandContext context, CommonCommandSettings settings)
InspectCommand Command Execute (CommandContext context, DiagnoseSettings settings)
override int Execute (CommandContext context, InspectSettings settings)
CommonCommandSettings CommandSettings Description ("Clear the database before collecting files.")][CommandOption("--clear-database|--clear")][DefaultValue(false)] public bool ClearDatabase
InspectSettings CommonCommandSettings Description ("Path to the source file to diagnose.")][CommandOption("--source-path|-s <SOURCE_PATH>")] public string? SourcePath
static internal class CommandExecutor RuntimeContext (string CultureCode, UiLanguage Language, bool NoWrap)
static int ExecuteCollect (CollectSettings settings, RuntimeContext runtime)
static int ExecuteGenerate (CommonCommandSettings settings, RuntimeContext runtime)
static int ExecuteFileOperations (CommonCommandSettings settings, RuntimeContext runtime)
static int ExecuteInspect (InspectSettings settings, RuntimeContext runtime)
static int ExecuteDiagnose (DiagnoseSettings settings, RuntimeContext runtime)
static string ReadCultureArgument (string[] args)
static string ResolveCultureCode (string rawCulture)
static UiLanguage ResolveLanguage (string cultureCode)
static string Get (UiLanguage language, string key)
internal readonly record struct LocalizedText (string English, string German, string French, string Filipino)
Variables
string ConfigPath { get
set
string Culture { get
bool NoWrap { get
string FilePath { get
string OutputPath { get
bool CopyPath { get
internal enum UiLanguage string
internal enum UiLanguage CultureAliases
static internal class ConsoleUi Texts
Enumeration Type Documentation
UiLanguage
enum UiLanguage
Enumerator
English
German
French
Filipino
Definition at line 588 of file Program.cs.
Function Documentation
Description() [1/2]
CommonCommandSettings CommandSettings Description ("Clear the database before collecting files.")
Definition at line 122 of file Program.cs.
References Description().
Referenced by Description().
Description() [2/2]
InspectSettings CommonCommandSettings Description ("Path to the source file to diagnose.")
Definition at line 146 of file Program.cs.
Execute() [1/4]
internal class ProgramHost Execute (CommandContext context, CollectSettings settings) static
Definition at line 12 of file Program.cs.
Execute() [2/4]
override int Execute (CommandContext context, CommonCommandSettings settings)
Definition at line 86 of file Program.cs.
Execute() [3/4]
InspectCommand Command Execute (CommandContext context, DiagnoseSettings settings)
Definition at line 104 of file Program.cs.
Execute() [4/4]
override int Execute::Execute (CommandContext context, InspectSettings settings)
Definition at line 116 of file Program.cs.
References CommandExecutor::ExecuteDiagnose(), and RuntimeContext().
ExecuteCollect()
int RuntimeContext::ExecuteCollect (CollectSettings settings, RuntimeContext runtime) static
Definition at line 575 of file Program.cs.
References AppLifetime::CurrentLanguage, AppLifetime::NoWrap, and RuntimeContext().
ExecuteDiagnose()
int RuntimeContext::ExecuteDiagnose (DiagnoseSettings settings, RuntimeContext runtime) static
Definition at line 743 of file Program.cs.
ExecuteFileOperations()
int RuntimeContext::ExecuteFileOperations (CommonCommandSettings settings, RuntimeContext runtime) static
Definition at line 612 of file Program.cs.
ExecuteGenerate()
int RuntimeContext::ExecuteGenerate (CommonCommandSettings settings, RuntimeContext runtime) static
Definition at line 598 of file Program.cs.
References CultureAliases.
ExecuteInspect()
int RuntimeContext::ExecuteInspect (InspectSettings settings, RuntimeContext runtime) static
Definition at line 626 of file Program.cs.
Get()
string Get (UiLanguage language, string key) static
Definition at line 838 of file Program.cs.
References Texts.
LocalizedText()
internal readonly record struct LocalizedText (string English, string German, string French, string Filipino)
References English, Filipino, French, German, LocalizedText(), and string.
Referenced by LocalizedText().
ReadCultureArgument()
string ReadCultureArgument (string[] args) static
Definition at line 610 of file Program.cs.
ResolveCultureCode()
string ResolveCultureCode (string rawCulture) static
Definition at line 624 of file Program.cs.
ResolveLanguage()
UiLanguage ResolveLanguage (string cultureCode) static
Definition at line 653 of file Program.cs.
Run() [1/2]
return ProgramHost Run (args)
Run() [2/2]
int Execute::Run (string[] args) static
Definition at line 80 of file Program.cs.
References CommandExecutor::ExecuteCollect(), and RuntimeContext().
RuntimeContext()
internal class CommandExecutor RuntimeContext (string CultureCode, UiLanguage Language, bool NoWrap) static
Definition at line 169 of file Program.cs.
Referenced by Execute(), GenerateCommand::Execute(), InspectCommand::Execute(), CommandExecutor::ExecuteCollect(), ExecuteCollect(), CommandExecutor::ExecuteDiagnose(), CommandExecutor::ExecuteFileOperations(), CommandExecutor::ExecuteGenerate(), CommandExecutor::ExecuteInspect(), Run(), ConsoleUi::WriteError(), ConsoleUi::WriteInfo(), ConsoleUi::WriteLine(), ConsoleUi::WriteProgress(), ConsoleUi::WriteSuccess(), ConsoleUi::WriteTitle(), and ConsoleUi::WriteWarning().
Variable Documentation
ConfigPath
string ConfigPath { get
Definition at line 143 of file Program.cs.
CopyPath
bool CopyPath { get
Definition at line 176 of file Program.cs.
Culture
string Culture { get
Definition at line 147 of file Program.cs.
Referenced by CommandExecutor::ExecuteDiagnose(), CommandExecutor::ExecuteInspect(), and LogCancelled().
CultureAliases
internal enum UiLanguage CultureAliases
Initial value:
= new(StringComparer.OrdinalIgnoreCase)
    {
        ["en"] = "en-US",
        ["en-en"] = "en-US",
        ["en-gb"] = "en-GB",
        ["de"] = "de-DE",
        ["fr"] = "fr-FR",
        ["fil"] = "fil-PH",
        ["tl"] = "fil-PH",
        ["ph"] = "fil-PH"
    }
Referenced by ExecuteGenerate().
FilePath
string FilePath { get
Definition at line 167 of file Program.cs.
NoWrap
bool NoWrap { get
Definition at line 152 of file Program.cs.
OutputPath
string OutputPath { get
Definition at line 171 of file Program.cs.
set
set
Definition at line 143 of file Program.cs.
Referenced by EnsureSupportedConfigurationVersion().
string
internal class ConsoleUi string
Referenced by LocalizedText().
Texts
internal class ConsoleUi Texts static
Referenced by Get().