FIRE: FIRE/FIRE.Console/Program.cs File Reference
Program.cs File Reference
Functions
if (args.Length==0)
for (int i=1;i< args.Length;i++)
if (string.IsNullOrWhiteSpace(configPath))
if (string.IsNullOrWhiteSpace(culture))
static int ShowHelp ()
static int ExecuteCollect (string configPath, string culture)
static int ExecuteGenerate (string configPath, string culture)
static int ExecuteOperations (string configPath, string culture)
static int ExecuteInspect (string[] args, string configPath, string culture)
static string TruncatePath (string path, int maxLength)
Truncates a file path to fit within the specified maximum length.
Variables
var command = args[0].ToLowerInvariant()
string configPath = null
string culture = null
return command switch
return command generate
Function Documentation
ExecuteCollect()
int ExecuteCollect (string configPath, string culture) static
Definition at line 85 of file Program.cs.
References configPath, culture, FIREConfigration::EnsureSupportedConfigurationVersion(), FIRECatalog(), FIREDatabase(), and FIREConfigration::Load().
ExecuteGenerate()
int ExecuteGenerate (string configPath, string culture) static
Definition at line 144 of file Program.cs.
References configPath, culture, FIREConfigration::EnsureSupportedConfigurationVersion(), FIRECatalog(), FIREDatabase(), and FIREConfigration::Load().
ExecuteInspect()
int ExecuteInspect (string[] args, string configPath, string culture) static
Definition at line 262 of file Program.cs.
References configPath, culture, FIREConfigration::EnsureSupportedConfigurationVersion(), FIRECatalog(), FIREDatabase(), FIREConfigration::Load(), and ShowHelp().
ExecuteOperations()
int ExecuteOperations (string configPath, string culture) static
Definition at line 203 of file Program.cs.
References configPath, culture, FIREConfigration::EnsureSupportedConfigurationVersion(), FIRECatalog(), FIREDatabase(), and FIREConfigration::Load().
for()
for ()
Definition at line 19 of file Program.cs.
References configPath, and culture.
if() [1/3]
if (args. Length = = 0)
Definition at line 8 of file Program.cs.
References ShowHelp().
if() [2/3]
if (string. IsNullOrWhiteSpaceconfigPath)
Definition at line 32 of file Program.cs.
References configPath, and ShowHelp().
if() [3/3]
if (string. IsNullOrWhiteSpaceculture)
Definition at line 39 of file Program.cs.
References culture, and ShowHelp().
ShowHelp()
int ShowHelp () static
Definition at line 56 of file Program.cs.
Referenced by ExecuteInspect(), if(), if(), and if().
TruncatePath()
string TruncatePath (string path, int maxLength) static
Truncates a file path to fit within the specified maximum length.
Definition at line 386 of file Program.cs.
Variable Documentation
command
var command = args[0].ToLowerInvariant()
Definition at line 14 of file Program.cs.
configPath
string configPath = null
Definition at line 15 of file Program.cs.
Referenced by ExecuteCollect(), ExecuteGenerate(), ExecuteInspect(), ExecuteOperations(), for(), and if().
culture
string culture = null
Definition at line 16 of file Program.cs.
Referenced by ExecuteCollect(), ExecuteGenerate(), ExecuteInspect(), ExecuteOperations(), for(), and if().
generate
return command generate
Initial value:
             => ExecuteGenerate(configPath, culture),
    "execute" => ExecuteOperations(configPath, culture),
    "inspect" => ExecuteInspect(args, configPath, culture),
    _ => ShowHelp()
}
Definition at line 50 of file Program.cs.
switch
return command switch
Initial value:
{
    "collect" => ExecuteCollect(configPath, culture)
Definition at line 47 of file Program.cs.